Repository refinedev/refine, pull requests merged in 2021-12, with the labels that each got.

#1277 comparison table
  documentation/docs/comparison.md
  documentation/sidebars.js
  documentation/versioned_docs/version-2.xx.xx/comparison.md
  documentation/versioned_sidebars/version-2.xx.xx-sidebars.json
Labels: pr-ready, auto-merge

#1280 fix custom routes wrapped layout wrapper
  packages/react-router/src/routeProvider.tsx
Labels: pr-ready, auto-merge

#1290 Sync Next and Version 2.xx Docs and Add livePorivder Examples
  documentation/docs/api-references/components/refine-config.md
  documentation/docs/api-references/interfaces.md
  documentation/docs/examples/live-provider/ably.md
  documentation/docs/examples/live-provider/supabase.md
  documentation/docs/getting-started/overview.md
  documentation/sidebars.js
  documentation/versioned_docs/version-2.xx.xx/api-references/components/refine-config.md
  documentation/versioned_docs/version-2.xx.xx/api-references/hooks/data/useList.md
  documentation/versioned_docs/version-2.xx.xx/api-references/hooks/data/useMany.md
  documentation/versioned_docs/version-2.xx.xx/api-references/hooks/data/useOne.md
  documentation/versioned_docs/version-2.xx.xx/api-references/hooks/field/useCheckboxGroup.md
  documentation/versioned_docs/version-2.xx.xx/api-references/hooks/field/useRadioGroup.md
  documentation/versioned_docs/version-2.xx.xx/api-references/hooks/field/useSelect.md
  documentation/versioned_docs/version-2.xx.xx/api-references/hooks/form/useDrawerForm.md
  documentation/versioned_docs/version-2.xx.xx/api-references/hooks/form/useForm.md
  documentation/versioned_docs/version-2.xx.xx/api-references/hooks/form/useModalForm.md
  documentation/versioned_docs/version-2.xx.xx/api-references/hooks/form/useStepsForm.md
  documentation/versioned_docs/version-2.xx.xx/api-references/hooks/live/usePublish.md
  documentation/versioned_docs/version-2.xx.xx/api-references/hooks/live/useSubscription.md
  documentation/versioned_docs/version-2.xx.xx/api-references/hooks/show/useShow.md
  documentation/versioned_docs/version-2.xx.xx/api-references/hooks/show/useSimpleList.md
  documentation/versioned_docs/version-2.xx.xx/api-references/hooks/table/useEditableTable.md
  documentation/versioned_docs/version-2.xx.xx/api-references/hooks/table/useTable.md
  documentation/versioned_docs/version-2.xx.xx/api-references/interfaces.md
  documentation/versioned_docs/version-2.xx.xx/api-references/providers/live-provider.md
  documentation/versioned_docs/version-2.xx.xx/examples/live-provider/ably.md
  documentation/versioned_docs/version-2.xx.xx/examples/live-provider/supabase.md
  documentation/versioned_docs/version-2.xx.xx/guides-and-concepts/real-time.md
  documentation/versioned_sidebars/version-2.xx.xx-sidebars.json
Labels: review-required, auto-merge

#1292 Remove supabase Example in Live Examples Folder
  documentation/docs/api-references/providers/live-provider.md
  documentation/docs/examples/data-provider/supabase.md
  documentation/docs/examples/live-provider/supabase.md
  documentation/sidebars.js
  documentation/versioned_docs/version-2.xx.xx/api-references/providers/live-provider.md
  documentation/versioned_docs/version-2.xx.xx/examples/data-provider/supabase.md
  documentation/versioned_docs/version-2.xx.xx/examples/live-provider/supabase.md
  documentation/versioned_docs/version-2.xx.xx/getting-started/overview.md
  documentation/versioned_sidebars/version-2.xx.xx-sidebars.json
Labels: pr-ready, review-required, auto-merge

#1293 fix liveMode prop type docs
  documentation/docs/api-references/hooks/data/useList.md
  documentation/docs/api-references/hooks/data/useMany.md
  documentation/docs/api-references/hooks/data/useOne.md
  documentation/docs/api-references/hooks/field/useCheckboxGroup.md
  documentation/docs/api-references/hooks/field/useRadioGroup.md
  documentation/docs/api-references/hooks/field/useSelect.md
  documentation/docs/api-references/hooks/form/useDrawerForm.md
  documentation/docs/api-references/hooks/form/useForm.md
  documentation/docs/api-references/hooks/form/useModalForm.md
  documentation/docs/api-references/hooks/form/useStepsForm.md
  documentation/docs/api-references/hooks/show/useShow.md
  documentation/docs/api-references/hooks/show/useSimpleList.md
  documentation/docs/api-references/hooks/table/useEditableTable.md
  documentation/docs/api-references/hooks/table/useTable.md
  documentation/versioned_docs/version-2.xx.xx/api-references/hooks/data/useList.md
  documentation/versioned_docs/version-2.xx.xx/api-references/hooks/data/useMany.md
  documentation/versioned_docs/version-2.xx.xx/api-references/hooks/data/useOne.md
  documentation/versioned_docs/version-2.xx.xx/api-references/hooks/field/useCheckboxGroup.md
  documentation/versioned_docs/version-2.xx.xx/api-references/hooks/field/useRadioGroup.md
  documentation/versioned_docs/version-2.xx.xx/api-references/hooks/field/useSelect.md
  documentation/versioned_docs/version-2.xx.xx/api-references/hooks/form/useDrawerForm.md
  documentation/versioned_docs/version-2.xx.xx/api-references/hooks/form/useForm.md
  documentation/versioned_docs/version-2.xx.xx/api-references/hooks/form/useModalForm.md
  documentation/versioned_docs/version-2.xx.xx/api-references/hooks/form/useStepsForm.md
  documentation/versioned_docs/version-2.xx.xx/api-references/hooks/show/useShow.md
  documentation/versioned_docs/version-2.xx.xx/api-references/hooks/show/useSimpleList.md
  documentation/versioned_docs/version-2.xx.xx/api-references/hooks/table/useEditableTable.md
  documentation/versioned_docs/version-2.xx.xx/api-references/hooks/table/useTable.md
Labels: documentation, review-required, auto-merge

#1306 pass metadata to mutate from useEditForm
  packages/core/src/hooks/form/useEditForm/useEditForm.ts
Labels: bug, review-required, auto-merge

#1304 Use label before resource
  packages/core/src/components/buttons/list/index.spec.tsx
  packages/core/src/components/buttons/list/index.tsx
  packages/core/src/components/crud/create/index.spec.tsx
  packages/core/src/components/crud/create/index.tsx
  packages/core/src/components/crud/edit/index.spec.tsx
  packages/core/src/components/crud/edit/index.tsx
  packages/core/src/components/crud/list/index.spec.tsx
  packages/core/src/components/crud/list/index.tsx
  packages/core/src/components/crud/show/index.spec.tsx
  packages/core/src/components/crud/show/index.tsx
Labels: enhancement, auto-merge

#1295 web3 signin guide template created
  documentation/docs/guides-and-concepts/web3/ethereum-signin.md
  documentation/sidebars.js
  documentation/static/img/guides-and-concepts/web3/customize.png
  documentation/static/img/guides-and-concepts/web3/dashboard.png
  documentation/static/img/guides-and-concepts/web3/ethereum-login.gif
  documentation/static/img/guides-and-concepts/web3/login.gif
  documentation/static/img/guides-and-concepts/web3/modal.png
  documentation/static/img/guides-and-concepts/web3/overview.gif
  documentation/versioned_docs/version-2.xx.xx/guides-and-concepts/web3/ethereum-signin.md
  documentation/versioned_sidebars/version-2.xx.xx-sidebars.json
  examples/web3/ethereumLogin/package.json
  examples/web3/ethereumLogin/public/ethereum.png
  examples/web3/ethereumLogin/public/ethereum.svg
  examples/web3/ethereumLogin/public/favicon.ico
  examples/web3/ethereumLogin/public/index.html
  examples/web3/ethereumLogin/public/refine.svg
  examples/web3/ethereumLogin/src/App.tsx
  examples/web3/ethereumLogin/src/authProvider.ts
  examples/web3/ethereumLogin/src/index.tsx
  examples/web3/ethereumLogin/src/interfaces/index.d.ts
  examples/web3/ethereumLogin/src/meta.json
  examples/web3/ethereumLogin/src/pages/dashboard.tsx
  examples/web3/ethereumLogin/src/pages/login.tsx
  examples/web3/ethereumLogin/src/pages/posts/create.tsx
  examples/web3/ethereumLogin/src/pages/posts/edit.tsx
  examples/web3/ethereumLogin/src/pages/posts/index.ts
  examples/web3/ethereumLogin/src/pages/posts/list.tsx
  examples/web3/ethereumLogin/src/pages/posts/show.tsx
  examples/web3/ethereumLogin/src/react-app-env.d.ts
  examples/web3/ethereumLogin/src/reportWebVitals.ts
  examples/web3/ethereumLogin/src/setupTests.ts
  examples/web3/ethereumLogin/src/utility/index.ts
  examples/web3/ethereumLogin/tsconfig.json
Labels: review-required

#1308 [Bug] Fix supabase contains containss filter operator
  packages/supabase/src/index.ts
  packages/supabase/test/getList/index.mock.ts
Labels: review-required, auto-merge

#1313 web3 login example added
  documentation/docs/examples/web3/signin-ethereum.md
  documentation/sidebars.js
  documentation/versioned_docs/version-2.xx.xx/examples/web3/signin-ethereum.md
  documentation/versioned_sidebars/version-2.xx.xx-sidebars.json
Labels: pr-ready, review-required, auto-merge

#1315 web3 blog added
  documentation/blog/2021-12-13-web3-refine.md
  documentation/static/img/blog/2021-12-13-web3-refine/login.gif
  documentation/static/img/blog/2021-12-13-web3-refine/overview.gif
Labels: review-required, auto-merge

#1319 fix useTable loading state
  packages/core/src/hooks/table/useTable/useTable.ts
Labels: auto-merge

#1297 Strapi v4 Data Provider and Example
  examples/dataProvider/strapi-v4/README.md
  examples/dataProvider/strapi-v4/package.json
  examples/dataProvider/strapi-v4/public/favicon.ico
  examples/dataProvider/strapi-v4/public/index.html
  examples/dataProvider/strapi-v4/public/manifest.json
  examples/dataProvider/strapi-v4/src/App.tsx
  examples/dataProvider/strapi-v4/src/constants.ts
  examples/dataProvider/strapi-v4/src/index.tsx
  examples/dataProvider/strapi-v4/src/interfaces/index.d.ts
  examples/dataProvider/strapi-v4/src/pages/categories/create.tsx
  examples/dataProvider/strapi-v4/src/pages/categories/edit.tsx
  examples/dataProvider/strapi-v4/src/pages/categories/index.tsx
  examples/dataProvider/strapi-v4/src/pages/categories/list.tsx
  examples/dataProvider/strapi-v4/src/pages/posts/create.tsx
  examples/dataProvider/strapi-v4/src/pages/posts/edit.tsx
  examples/dataProvider/strapi-v4/src/pages/posts/index.ts
  examples/dataProvider/strapi-v4/src/pages/posts/list.tsx
  examples/dataProvider/strapi-v4/src/react-app-env.d.ts
  examples/dataProvider/strapi-v4/tsconfig.json
  packages/core/src/hooks/data/useCreate.ts
  packages/core/src/hooks/data/useCustom.ts
  packages/core/src/hooks/data/useList.ts
  packages/core/src/hooks/data/useMany.ts
  packages/core/src/hooks/data/useOne.ts
  packages/strapi-v4/LICENSE
  packages/strapi-v4/README.md
  packages/strapi-v4/jest.config.js
  packages/strapi-v4/package.json
  packages/strapi-v4/src/dataProvider.ts
  packages/strapi-v4/src/helpers/auth.ts
  packages/strapi-v4/src/helpers/index.ts
  packages/strapi-v4/src/helpers/normalize.ts
  packages/strapi-v4/src/hooks/index.ts
  packages/strapi-v4/src/hooks/upload.ts
  packages/strapi-v4/src/index.ts
  packages/strapi-v4/test/auth/index.mock.ts
  packages/strapi-v4/test/auth/index.spec.ts
  packages/strapi-v4/test/dataProvider/index.mock.ts
  packages/strapi-v4/test/dataProvider/index.spec.ts
  packages/strapi-v4/test/jest.setup.ts
  packages/strapi-v4/tsconfig.json
Labels: review-required, auto-merge

#1296 Add appwrite data provider
  documentation/blog/2021-11-26-refine-vs-react-admin.md
  documentation/blog/2021-11-29-refine-vs-admin-bro.md
  documentation/docs/api-references/providers/data-provider.md
  documentation/docs/getting-started/overview.md
  documentation/docs/tutorial.md
  documentation/package-lock.json
  documentation/src/components/key-features/index.js
  documentation/static/icons/backends/appwrite.png
  documentation/static/icons/backends/appwrite@2x.png
  documentation/static/icons/backends/java.png
  documentation/static/icons/backends/java@2x.png
  documentation/versioned_docs/version-2.xx.xx/api-references/providers/data-provider.md
  documentation/versioned_docs/version-2.xx.xx/getting-started/overview.md
  documentation/versioned_docs/version-2.xx.xx/tutorial.md
  examples/dataProvider/appwrite/.gitignore
  examples/dataProvider/appwrite/package.json
  examples/dataProvider/appwrite/public/favicon.ico
  examples/dataProvider/appwrite/public/index.html
  examples/dataProvider/appwrite/public/manifest.json
  examples/dataProvider/appwrite/public/refine.svg
  examples/dataProvider/appwrite/src/App.tsx
  examples/dataProvider/appwrite/src/index.tsx
  examples/dataProvider/appwrite/src/interfaces/index.d.ts
  examples/dataProvider/appwrite/src/pages/login/index.tsx
  examples/dataProvider/appwrite/src/pages/login/styles.css
  examples/dataProvider/appwrite/src/pages/posts/create.tsx
  examples/dataProvider/appwrite/src/pages/posts/edit.tsx
  examples/dataProvider/appwrite/src/pages/posts/index.tsx
  examples/dataProvider/appwrite/src/pages/posts/list.tsx
  examples/dataProvider/appwrite/src/pages/posts/show.tsx
  examples/dataProvider/appwrite/src/react-app-env.d.ts
  examples/dataProvider/appwrite/src/utility/appwriteClient.ts
  examples/dataProvider/appwrite/src/utility/index.ts
  examples/dataProvider/appwrite/src/utility/normalize.ts
  examples/dataProvider/appwrite/tsconfig.json
  packages/appwrite/LICENSE
  packages/appwrite/README.md
  packages/appwrite/jest.config.js
  packages/appwrite/package.json
  packages/appwrite/src/index.ts
  packages/appwrite/test/appwriteClient.ts
  packages/appwrite/test/jest.setup.ts
  packages/appwrite/tsconfig.json
  packages/core/package-lock.json
Labels: enhancement, review-required, auto-merge

#1368 Strapi v4 guide
  documentation/docs/guides-and-concepts/data-provider/strapi-v4.md
  documentation/sidebars.js
  documentation/static/img/guides-and-concepts/data-provider/strapi-v4/category.png
  documentation/static/img/guides-and-concepts/data-provider/strapi-v4/draft.png
  documentation/static/img/guides-and-concepts/data-provider/strapi-v4/locale.gif
  documentation/static/img/guides-and-concepts/data-provider/strapi-v4/locale.png
  documentation/static/img/guides-and-concepts/data-provider/strapi-v4/publication.gif
  documentation/static/img/guides-and-concepts/data-provider/strapi-v4/published.png
  documentation/static/img/guides-and-concepts/data-provider/strapi-v4/selection.png
  documentation/versioned_docs/version-2.xx.xx/guides-and-concepts/data-provider/strapi-v4.md
  documentation/versioned_sidebars/version-2.xx.xx-sidebars.json
  examples/dataProvider/strapi-v4/src/pages/posts/edit.tsx
Labels: review-required, auto-merge

#1370 update example and docs for RefreshButton
  documentation/docs/guides-and-concepts/data-provider/graphql.md
  documentation/versioned_docs/version-2.xx.xx/guides-and-concepts/data-provider/graphql.md
  examples/dataProvider/strapi-graphql/src/pages/posts/edit.tsx
  examples/dataProvider/strapi-graphql/src/pages/posts/show.tsx
Labels: documentation, review-required, auto-merge

#1380 appwrite guide
  documentation/docs/guides-and-concepts/data-provider/appwrite.md
  documentation/sidebars.js
  documentation/static/img/guides-and-concepts/data-provider/appwrite/category.png
  documentation/static/img/guides-and-concepts/data-provider/appwrite/create.gif
  documentation/static/img/guides-and-concepts/data-provider/appwrite/edit.png
  documentation/static/img/guides-and-concepts/data-provider/appwrite/list.png
  documentation/static/img/guides-and-concepts/data-provider/appwrite/login.png
  documentation/static/img/guides-and-concepts/data-provider/appwrite/permission.png
  documentation/static/img/guides-and-concepts/data-provider/appwrite/posts.png
  documentation/static/img/guides-and-concepts/data-provider/appwrite/user.png
  documentation/versioned_docs/version-2.xx.xx/guides-and-concepts/data-provider/appwrite.md
  documentation/versioned_sidebars/version-2.xx.xx-sidebars.json
Labels: review-required, auto-merge

#1383 base64 file upload blog
  documentation/blog/2021-12-22-base64-upload.md
  documentation/static/img/blog/2021-12-22-base64-upload/overview.png
  documentation/static/img/blog/2021-12-22-base64-upload/upload.png
Labels: pr-ready, review-required, auto-merge

#1388 [Bug] Fix Airtable example
  examples/dataProvider/airtable/src/App.tsx
  examples/dataProvider/airtable/src/pages/posts/list.tsx
  examples/dataProvider/airtable/src/pages/posts/show.tsx
Labels: review-required, auto-merge

#1382 add tests and fix some parts of Appwrite data provider
  documentation/docs/examples/data-provider/appwrite.md
  documentation/docs/guides-and-concepts/data-provider/appwrite.md
  documentation/sidebars.js
  documentation/versioned_docs/version-2.xx.xx/examples/data-provider/appwrite.md
  documentation/versioned_docs/version-2.xx.xx/guides-and-concepts/data-provider/appwrite.md
  documentation/versioned_sidebars/version-2.xx.xx-sidebars.json
  examples/dataProvider/appwrite/package.json
  examples/dataProvider/appwrite/src/App.tsx
  examples/dataProvider/appwrite/src/interfaces/index.d.ts
  examples/dataProvider/appwrite/src/pages/login/index.tsx
  examples/dataProvider/appwrite/src/pages/posts/create.tsx
  examples/dataProvider/appwrite/src/pages/posts/edit.tsx
  examples/dataProvider/appwrite/src/pages/posts/list.tsx
  examples/dataProvider/appwrite/src/pages/posts/show.tsx
  examples/dataProvider/appwrite/src/utility/appwriteClient.ts
  packages/appwrite/jest.config.js
  packages/appwrite/src/index.ts
  packages/appwrite/test/appwriteClient.ts
  packages/appwrite/test/create/index.mock.ts
  packages/appwrite/test/create/index.spec.ts
  packages/appwrite/test/createMany/index.mock.ts
  packages/appwrite/test/createMany/index.spec.ts
  packages/appwrite/test/custom/index.spec.ts
  packages/appwrite/test/deleteMany/index.mock.ts
  packages/appwrite/test/deleteMany/index.spec.ts
  packages/appwrite/test/deleteOne/index.mock.ts
  packages/appwrite/test/deleteOne/index.spec.ts
  packages/appwrite/test/getApiUrl/index.spec.ts
  packages/appwrite/test/getList/index.mock.ts
  packages/appwrite/test/getList/index.spec.ts
  packages/appwrite/test/getMany/index.mock.ts
  packages/appwrite/test/getMany/index.spec.ts
  packages/appwrite/test/getOne/index.mock.ts
  packages/appwrite/test/getOne/index.spec.ts
  packages/appwrite/test/jest.setup.ts
  packages/appwrite/test/liveProvider/index.spec.ts
  packages/appwrite/test/update/index.mock.ts
  packages/appwrite/test/update/index.spec.ts
  packages/appwrite/test/updateMany/index.mock.ts
  packages/appwrite/test/updateMany/index.spec.ts
Labels: bug, pr-onhold, review-required, auto-merge

#1389 multipart upload blog added
  documentation/blog/2021-12-27-multipart-upload.md
  documentation/static/img/blog/2021-12-27-multipart-upload/overview.gif
  documentation/static/img/blog/2021-12-27-multipart-upload/upload.png
Labels: review-required, auto-merge

#1391 add fetchSize and onSearch with examples
  documentation/docs/api-references/hooks/field/useSelect.md
  documentation/versioned_docs/version-2.xx.xx/api-references/hooks/field/useSelect.md
  examples/field/useSelect/src/pages/posts/create.tsx
  examples/field/useSelect/src/pages/posts/edit.tsx
  examples/field/useSelect/src/pages/posts/list.tsx
  packages/core/src/hooks/fields/useSelect/index.spec.ts
  packages/core/src/hooks/fields/useSelect/index.ts
Labels: enhancement, pr-ready, auto-merge

#1395 Fix strapi-graphql useUpdate mutation
  examples/dataProvider/strapi-graphql/src/App.tsx
  examples/dataProvider/strapi-graphql/src/pages/posts/edit.tsx
  packages/strapi-graphql/src/index.ts
  packages/strapi-graphql/test/gqlClient.ts
  packages/strapi-graphql/test/update/index.mock.ts
  packages/strapi-graphql/test/update/index.spec.ts
  packages/strapi-graphql/test/updateMany/index.spec.ts
Labels: pr-ready, auto-merge

#1399 add Firebase data provider
  README.md
  documentation/docs/api-references/providers/data-provider.md
  documentation/docs/getting-started/overview.md
  documentation/docs/tutorial.md
  documentation/src/components/key-features/index.js
  documentation/versioned_docs/version-1.0.xx/tutorial.md
  documentation/versioned_docs/version-2.xx.xx/api-references/providers/data-provider.md
  documentation/versioned_docs/version-2.xx.xx/getting-started/overview.md
  documentation/versioned_docs/version-2.xx.xx/tutorial.md
  packages/core/README.md
Labels: review-required, auto-merge
