Repository refinedev/refine, pull requests merged in 2021-09, with the labels that each got.

#1108 add strapi graphql example to doc examples
  documentation/docs/examples/data-provider/strapi-graphql.md
  documentation/sidebars.js
Labels: pr-ready, review-required, auto-merge

#1109 Some fixes on tutorial doc
  documentation/docs/tutorial.md
  documentation/static/img/tutorial/create.gif
  documentation/static/img/tutorial/edit.gif
  documentation/static/img/tutorial/resource-1.png
  documentation/static/img/tutorial/resource-2.png
  documentation/static/img/tutorial/show.gif
  logo.png
Labels: documentation, auto-merge

#1111 remove buggy styles of Sider
  documentation/docs/api-references/hooks/resource/useMenu.md
  packages/core/src/assets/styles/custom-theme.less
  packages/core/src/assets/styles/styles.min.css
  packages/core/src/components/layoutWrapper/components/sider/index.tsx
Labels: bug, enhancement, auto-merge

#1113 move and rename theming script
  package.json
  packages/core/package.json
Labels: auto-merge

#1116 fix typo
  documentation/src/components/fast-and-flexible/index.js
Labels: pr-ready

#1121 Fixing the tests with routerProvider
  package-lock.json
  package.json
  packages/core/src/components/containers/refine/index.spec.tsx
  packages/core/src/components/containers/refine/index.tsx
  packages/core/src/components/containers/routeProvider/index.spec.tsx
  packages/core/src/components/containers/routeProvider/index.tsx
  packages/core/src/components/layoutWrapper/index.spec.tsx
  packages/core/src/components/routeChangeHandler/index.tsx
  packages/core/src/hooks/refine/useRouterContext.ts
  packages/core/src/hooks/resource/useMenu/index.tsx
  packages/core/src/hooks/resource/useMenu/useMenu.spec.tsx
  packages/core/test/dataMocks.ts
  packages/core/test/index.tsx
Labels: pr-ready, review-required, auto-merge
