Repository refinedev/refine, pull requests merged in 2021-11, with the labels that each got.

#1193 fix id return value of some hooks
  packages/core/src/hooks/form/useEditForm/useEditForm.spec.tsx
  packages/core/src/hooks/form/useEditForm/useEditForm.ts
  packages/core/src/hooks/form/useModalForm/useModalForm.spec.tsx
  packages/core/src/hooks/show/useShow.spec.tsx
  packages/core/src/hooks/show/useShow.ts
Labels: bug, pr-ready, auto-merge

#1205 Update Migration Guide
  documentation/docs/migration-guide.md
Labels: review-required, auto-merge

#1208 Demo page for documentation
  documentation/Dockerfile
  documentation/docusaurus.config.js
  documentation/package-lock.json
  documentation/package.json
  documentation/src/css/demo-page.css
  documentation/src/css/split-pane.css
  documentation/src/pages/demo.js
  documentation/static/demo/nextjs-client.png
  documentation/static/demo/react-admin.png
Labels: pr-ready, review-required, auto-merge

#1210 Customizable React Query Devtools
  documentation/docs/api-references/components/refine-config.md
  packages/core/src/components/containers/refine/index.tsx
Labels: review-required, auto-merge

#1212 Add enterprise contact page
  documentation/docusaurus.config.js
  documentation/package-lock.json
  documentation/package.json
  documentation/src/css/custom.css
  documentation/src/pages/enterprise/index.tsx
  documentation/src/pages/enterprise/styles.module.css
  documentation/src/pages/privacy-policy.md
  documentation/static/contact-page/contact_bg.png
  documentation/static/contact-page/contact_rise.png
Labels: review-required

#1219 update pageData to initialData
  documentation/docs/guides-and-concepts/ssr-nextjs.md
  examples/refine-next/pages/[resource]/index.tsx
  packages/nextjs-router/src/nextRouteComponent.tsx
Labels: review-required, auto-merge

#1220 Switch Toggle for Demo Pages
  examples/fineFoods/admin/src/App.tsx
  examples/fineFoods/admin/src/components/index.ts
  examples/fineFoods/admin/src/components/offLayoutArea/index.tsx
  examples/fineFoods/admin/src/components/offLayoutArea/style.less
  examples/fineFoods/client/pages/_app.tsx
  examples/fineFoods/client/src/components/index.ts
  examples/fineFoods/client/src/components/offLayoutArea/index.tsx
  examples/fineFoods/client/src/components/offLayoutArea/style.less
Labels: review-required, auto-merge

#1222 Add codemod package
  package-lock.json
  package.json
  packages/codemod/LICENSE
  packages/codemod/jest.config.js
  packages/codemod/package-lock.json
  packages/codemod/package.json
  packages/codemod/src/helpers/checkPackageLock.ts
  packages/codemod/src/helpers/index.ts
  packages/codemod/src/helpers/install.ts
  packages/codemod/src/index.ts
  packages/codemod/src/transformations/refine1-to-refine2.ts
  packages/codemod/tsconfig.json
Labels: review-required, auto-merge

#1223 [DOCS] Add codemod docs
  documentation/docs/migration-guide.md
  packages/codemod/README.md
Labels: review-required, auto-merge

#1224 Add Product Hunt Badge
  README.md
  documentation/src/components/hero/index.js
  documentation/src/components/hero/styles.module.css
Labels: pr-ready, review-required, auto-merge

#1228 add docs for Link
  documentation/docs/migration-guide.md
  documentation/versioned_docs/version-2.xx.xx/migration-guide.md
Labels: documentation, pr-ready, auto-merge

#1235 upgrade refine-nextjs-router - next.js@12
  examples/fineFoods/client/package.json
  examples/i18n/nextjs/package.json
  examples/refine-next/package.json
  examples/refine-next/tsconfig.json
  packages/nextjs-router/package.json
Labels: review-required, auto-merge

#1237 nextjs 12 support
  examples/fineFoods/client/package-lock.json
  examples/fineFoods/client/package.json
  examples/fineFoods/client/tsconfig.json
  examples/i18n/nextjs/package.json
  examples/refine-next/package.json
  examples/refine-next/tsconfig.json
  lerna.json
  packages/nextjs-router/package.json
Labels: review-required, auto-merge

#1241 blog image changed
  documentation/blog/2021-11-12-issue-tracker-refine.md
Labels: review-required, auto-merge

#1247 blog moved to refine blog
  documentation/blog/2021-10-6-migrating-react-admin-application-to-refine.md
  documentation/blog/2021-11-12-issue-tracker-refine.md
  documentation/blog/authors.yml
  documentation/static/img/blog/2021-10-6-migrating-react-admin-to-refine/react_admin.png
  documentation/static/img/blog/2021-10-6-migrating-react-admin-to-refine/react_admin_create.png
  documentation/static/img/blog/2021-10-6-migrating-react-admin-to-refine/refine_table.png
  documentation/static/img/blog/2021-10-6-migrating-react-admin-to-refine/sider.png
Labels: pr-ready, auto-merge

#1248 feedback panel blog added
  documentation/blog/2021-10-4-feedback-admin-panel.md
  documentation/blog/authors.yml
  documentation/static/img/blog/2021-10-4-feedback-admin-panel/feedback.png
  documentation/static/img/blog/2021-10-4-feedback-admin-panel/feedback_overview.gif
  documentation/static/img/blog/2021-10-4-feedback-admin-panel/feedbacks.png
  documentation/static/img/blog/2021-10-4-feedback-admin-panel/header.png
  documentation/static/img/blog/2021-10-4-feedback-admin-panel/refine_welcome.png
  documentation/static/img/blog/2021-10-4-feedback-admin-panel/signin.png
  documentation/static/img/blog/2021-10-4-feedback-admin-panel/strapi_content.png
  documentation/static/img/blog/2021-10-4-feedback-admin-panel/user.png
  documentation/static/img/blog/2021-10-4-feedback-admin-panel/widgets.gif
  examples/blog/refeedback/README.md
  examples/blog/refeedback/package.json
  examples/blog/refeedback/public/favicon.ico
  examples/blog/refeedback/public/index.html
  examples/blog/refeedback/public/refeedback.png
  examples/blog/refeedback/public/refine-collapsed.svg
  examples/blog/refeedback/public/refine.svg
  examples/blog/refeedback/src/App.tsx
  examples/blog/refeedback/src/authProvider.ts
  examples/blog/refeedback/src/components/feedback/index.tsx
  examples/blog/refeedback/src/components/feedback/inputPage.tsx
  examples/blog/refeedback/src/components/feedback/typePage.tsx
  examples/blog/refeedback/src/components/header/index.tsx
  examples/blog/refeedback/src/components/index.ts
  examples/blog/refeedback/src/components/layout/index.tsx
  examples/blog/refeedback/src/components/offLayoutArea/index.tsx
  examples/blog/refeedback/src/index.tsx
  examples/blog/refeedback/src/interfaces/index.d.ts
  examples/blog/refeedback/src/meta.json
  examples/blog/refeedback/src/pages/FeedbackList.tsx
  examples/blog/refeedback/src/react-app-env.d.ts
  examples/blog/refeedback/src/reportWebVitals.ts
  examples/blog/refeedback/src/setupTests.ts
  examples/blog/refeedback/src/styles/global.css
  examples/blog/refeedback/tsconfig.json
Labels: pr-ready, auto-merge

#1249 nestjs admin panel blog added
  documentation/blog/2021-10-4-admin-panel-with-nestjs.md
  documentation/blog/authors.yml
  documentation/static/img/blog/2021-10-4-admin-panel-with-nestjs/api.png
  documentation/static/img/blog/2021-10-4-admin-panel-with-nestjs/refine_job.png
  documentation/static/img/blog/2021-10-4-admin-panel-with-nestjs/refine_sample.png
  examples/blog/jobPosting/README.md
  examples/blog/jobPosting/craco.config.js
  examples/blog/jobPosting/package.json
  examples/blog/jobPosting/public/favicon.ico
  examples/blog/jobPosting/public/index.html
  examples/blog/jobPosting/public/refine-collapsed.svg
  examples/blog/jobPosting/public/refine.svg
  examples/blog/jobPosting/src/App.tsx
  examples/blog/jobPosting/src/components/footer/index.tsx
  examples/blog/jobPosting/src/components/header/index.tsx
  examples/blog/jobPosting/src/components/index.ts
  examples/blog/jobPosting/src/components/layout/index.tsx
  examples/blog/jobPosting/src/components/offLayoutArea/index.tsx
  examples/blog/jobPosting/src/components/sider/index.tsx
  examples/blog/jobPosting/src/components/sider/styles.ts
  examples/blog/jobPosting/src/components/title/index.tsx
  examples/blog/jobPosting/src/index.tsx
  examples/blog/jobPosting/src/interfaces/index.d.ts
  examples/blog/jobPosting/src/meta.json
  examples/blog/jobPosting/src/pages/companies/create.tsx
  examples/blog/jobPosting/src/pages/companies/edit.tsx
  examples/blog/jobPosting/src/pages/companies/index.ts
  examples/blog/jobPosting/src/pages/companies/list.tsx
  examples/blog/jobPosting/src/pages/companies/show.tsx
  examples/blog/jobPosting/src/pages/jobs/create.tsx
  examples/blog/jobPosting/src/pages/jobs/edit.tsx
  examples/blog/jobPosting/src/pages/jobs/index.ts
  examples/blog/jobPosting/src/pages/jobs/list.tsx
  examples/blog/jobPosting/src/pages/jobs/show.tsx
  examples/blog/jobPosting/src/react-app-env.d.ts
  examples/blog/jobPosting/src/reportWebVitals.ts
  examples/blog/jobPosting/src/setupTests.ts
  examples/blog/jobPosting/src/styles/antd.less
  examples/blog/jobPosting/tsconfig.json
Labels: pr-ready, review-required, auto-merge

#1251 Simple web app blog
  documentation/blog/2021-10-4-simple-web-application.md
  documentation/blog/authors.yml
  documentation/static/img/blog/2021-10-4-simple-web-application/cli.png
  documentation/static/img/blog/2021-10-4-simple-web-application/create.png
  documentation/static/img/blog/2021-10-4-simple-web-application/detailed.png
  documentation/static/img/blog/2021-10-4-simple-web-application/edit.png
  documentation/static/img/blog/2021-10-4-simple-web-application/movies.png
  documentation/static/img/blog/2021-10-4-simple-web-application/movies_all.png
  documentation/static/img/blog/2021-10-4-simple-web-application/show.png
  documentation/static/img/blog/2021-10-4-simple-web-application/signin.png
  examples/blog/refineflix/README.MD
  examples/blog/refineflix/package.json
  examples/blog/refineflix/public/favicon.ico
  examples/blog/refineflix/public/index.html
  examples/blog/refineflix/public/refine-collapsed.svg
  examples/blog/refineflix/public/refine.svg
  examples/blog/refineflix/src/App.tsx
  examples/blog/refineflix/src/authProvider.ts
  examples/blog/refineflix/src/components/footer/index.tsx
  examples/blog/refineflix/src/components/header/index.tsx
  examples/blog/refineflix/src/components/index.ts
  examples/blog/refineflix/src/components/layout/index.tsx
  examples/blog/refineflix/src/components/offLayoutArea/index.tsx
  examples/blog/refineflix/src/components/sider/index.tsx
  examples/blog/refineflix/src/components/sider/styles.ts
  examples/blog/refineflix/src/components/title/index.tsx
  examples/blog/refineflix/src/index.tsx
  examples/blog/refineflix/src/interfaces/index.d.ts
  examples/blog/refineflix/src/meta.json
  examples/blog/refineflix/src/pages/admin/movies/create.tsx
  examples/blog/refineflix/src/pages/admin/movies/edit.tsx
  examples/blog/refineflix/src/pages/admin/movies/index.tsx
  examples/blog/refineflix/src/pages/admin/movies/list.tsx
  examples/blog/refineflix/src/pages/admin/movies/show.tsx
  examples/blog/refineflix/src/pages/login/index.tsx
  examples/blog/refineflix/src/pages/login/styles.css
  examples/blog/refineflix/src/pages/movies/index.ts
  examples/blog/refineflix/src/pages/movies/list.tsx
  examples/blog/refineflix/src/pages/movies/show.tsx
  examples/blog/refineflix/src/react-app-env.d.ts
  examples/blog/refineflix/src/reportWebVitals.ts
  examples/blog/refineflix/src/setupTests.ts
  examples/blog/refineflix/src/utility/index.ts
  examples/blog/refineflix/src/utility/normalize.ts
  examples/blog/refineflix/src/utility/supabaseClient.ts
  examples/blog/refineflix/tsconfig.json
Labels: pr-ready, auto-merge

#1256 manage hackathons blog added
  documentation/blog/2021-10-4-manage-hackatons.md
  documentation/blog/authors.yml
  documentation/static/img/blog/2021-10-4-manage-hackathons/create.png
  documentation/static/img/blog/2021-10-4-manage-hackathons/hackathons.png
  examples/blog/hackathonize/README.MD
  examples/blog/hackathonize/package.json
  examples/blog/hackathonize/public/favicon.ico
  examples/blog/hackathonize/public/index.html
  examples/blog/hackathonize/src/App.tsx
  examples/blog/hackathonize/src/authProvider.ts
  examples/blog/hackathonize/src/index.tsx
  examples/blog/hackathonize/src/interfaces/index.ts
  examples/blog/hackathonize/src/meta.json
  examples/blog/hackathonize/src/pages/criterias/create.tsx
  examples/blog/hackathonize/src/pages/criterias/edit.tsx
  examples/blog/hackathonize/src/pages/criterias/index.ts
  examples/blog/hackathonize/src/pages/criterias/list.tsx
  examples/blog/hackathonize/src/pages/criterias/show.tsx
  examples/blog/hackathonize/src/pages/dashboard/index.tsx
  examples/blog/hackathonize/src/pages/hackathoners/create.tsx
  examples/blog/hackathonize/src/pages/hackathoners/edit.tsx
  examples/blog/hackathonize/src/pages/hackathoners/index.ts
  examples/blog/hackathonize/src/pages/hackathoners/list.tsx
  examples/blog/hackathonize/src/pages/hackathoners/show.tsx
  examples/blog/hackathonize/src/pages/hackathons/create.tsx
  examples/blog/hackathonize/src/pages/hackathons/edit.tsx
  examples/blog/hackathonize/src/pages/hackathons/index.ts
  examples/blog/hackathonize/src/pages/hackathons/list.tsx
  examples/blog/hackathonize/src/pages/hackathons/show.tsx
  examples/blog/hackathonize/src/pages/login/index.tsx
  examples/blog/hackathonize/src/pages/login/styles.css
  examples/blog/hackathonize/src/pages/projects/create.tsx
  examples/blog/hackathonize/src/pages/projects/edit.tsx
  examples/blog/hackathonize/src/pages/projects/index.ts
  examples/blog/hackathonize/src/pages/projects/list.tsx
  examples/blog/hackathonize/src/pages/projects/show.tsx
  examples/blog/hackathonize/src/pages/teams/create.tsx
  examples/blog/hackathonize/src/pages/teams/edit.tsx
  examples/blog/hackathonize/src/pages/teams/index.ts
  examples/blog/hackathonize/src/pages/teams/list.tsx
  examples/blog/hackathonize/src/pages/teams/show.tsx
  examples/blog/hackathonize/src/react-app-env.d.ts
  examples/blog/hackathonize/src/reportWebVitals.ts
  examples/blog/hackathonize/src/setupTests.ts
  examples/blog/hackathonize/src/utility/index.ts
  examples/blog/hackathonize/src/utility/supabaseClient.ts
  examples/blog/hackathonize/tsconfig.json
Labels: pr-ready, review-required

#1257 mail subscription blog added
  documentation/blog/2021-10-25-mail-subscription-with-refine.md
  documentation/blog/2021-10-6-migrating-react-admin-application-to-refine.md
  documentation/static/img/blog/2021-10-25-mail-subscription-with-refine/auth.png
  documentation/static/img/blog/2021-10-25-mail-subscription-with-refine/create.gif
  documentation/static/img/blog/2021-10-25-mail-subscription-with-refine/dummy_data.png
  documentation/static/img/blog/2021-10-25-mail-subscription-with-refine/login.gif
  documentation/static/img/blog/2021-10-25-mail-subscription-with-refine/messages.png
  documentation/static/img/blog/2021-10-25-mail-subscription-with-refine/overview.png
  documentation/static/img/blog/2021-10-25-mail-subscription-with-refine/refine_messages.png
  documentation/static/img/blog/2021-10-25-mail-subscription-with-refine/refine_subs.png
  documentation/static/img/blog/2021-10-25-mail-subscription-with-refine/refine_welcome.png
  documentation/static/img/blog/2021-10-25-mail-subscription-with-refine/send.gif
  documentation/static/img/blog/2021-10-25-mail-subscription-with-refine/signin.png
  documentation/static/img/blog/2021-10-25-mail-subscription-with-refine/strapi.png
  documentation/static/img/blog/2021-10-25-mail-subscription-with-refine/subscribers.png
  examples/blog/mailSubscription/README.MD
  examples/blog/mailSubscription/package.json
  examples/blog/mailSubscription/public/favicon.ico
  examples/blog/mailSubscription/public/index.html
  examples/blog/mailSubscription/public/refine-collapsed.svg
  examples/blog/mailSubscription/public/refine.svg
  examples/blog/mailSubscription/src/App.tsx
  examples/blog/mailSubscription/src/authProvider.ts
  examples/blog/mailSubscription/src/components/footer/index.tsx
  examples/blog/mailSubscription/src/components/header/index.tsx
  examples/blog/mailSubscription/src/components/index.ts
  examples/blog/mailSubscription/src/components/layout/index.tsx
  examples/blog/mailSubscription/src/components/offLayoutArea/index.tsx
  examples/blog/mailSubscription/src/components/sider/index.tsx
  examples/blog/mailSubscription/src/components/sider/styles.ts
  examples/blog/mailSubscription/src/components/title/index.tsx
  examples/blog/mailSubscription/src/index.tsx
  examples/blog/mailSubscription/src/interfaces/index.d.ts
  examples/blog/mailSubscription/src/meta.json
  examples/blog/mailSubscription/src/pages/mail/create.tsx
  examples/blog/mailSubscription/src/pages/mail/index.tsx
  examples/blog/mailSubscription/src/pages/mail/list.tsx
  examples/blog/mailSubscription/src/pages/subscriber/create.tsx
  examples/blog/mailSubscription/src/pages/subscriber/index.tsx
  examples/blog/mailSubscription/src/pages/subscriber/list.tsx
  examples/blog/mailSubscription/src/react-app-env.d.ts
  examples/blog/mailSubscription/src/reportWebVitals.ts
  examples/blog/mailSubscription/src/setupTests.ts
  examples/blog/mailSubscription/tsconfig.json
Labels: pr-ready, review-required, auto-merge

#1261 blog repo url and title edited
  documentation/blog/2021-10-4-admin-panel-with-nestjs.md
  documentation/blog/2021-11-12-issue-tracker-refine.md
Labels: pr-onhold, review-required, auto-merge

#1264 fix useForm action on nested pages
  documentation/docs/api-references/components/buttons/clone.md
  documentation/docs/api-references/components/refine-config.md
  documentation/docs/api-references/hooks/form/useForm.md
  documentation/versioned_docs/version-2.xx.xx/api-references/components/buttons/clone.md
  documentation/versioned_docs/version-2.xx.xx/api-references/components/refine-config.md
  documentation/versioned_docs/version-2.xx.xx/api-references/hooks/form/useForm.md
  packages/core/src/components/buttons/clone/index.spec.tsx
  packages/core/src/hooks/form/useCloneForm/useCloneForm.spec.tsx
  packages/core/src/hooks/form/useCloneForm/useCloneForm.ts
  packages/core/src/hooks/form/useDrawerForm/useDrawerForm.ts
  packages/core/src/hooks/form/useEditForm/useEditForm.ts
  packages/core/src/hooks/form/useForm.ts
  packages/core/src/hooks/form/useModalForm/useModalForm.ts
  packages/core/src/hooks/navigation/index.spec.tsx
  packages/core/src/hooks/navigation/index.ts
  packages/core/src/interfaces/resourceRouterParams.ts
  packages/nextjs-router/src/nextRouteComponent.tsx
  packages/react-location/src/resourceComponent.tsx
  packages/react-location/src/routerComponent.tsx
  packages/react-router/src/routeProvider.tsx
Labels: review-required

#1267 add dayjs and antd to peerDependencies
  examples/fineFoods/admin/package-lock.json
  examples/fineFoods/admin/package.json
  packages/core/package-lock.json
  packages/core/package.json
Labels: review-required, auto-merge

#1266 refine 2.2.1
  documentation/docs/api-references/components/buttons/clone.md
  documentation/docs/api-references/components/refine-config.md
  documentation/docs/api-references/hooks/form/useForm.md
  documentation/versioned_docs/version-2.xx.xx/api-references/components/buttons/clone.md
  documentation/versioned_docs/version-2.xx.xx/api-references/components/refine-config.md
  documentation/versioned_docs/version-2.xx.xx/api-references/hooks/form/useForm.md
  examples/fineFoods/admin/package-lock.json
  examples/fineFoods/admin/package.json
  examples/fineFoods/client/package-lock.json
  examples/fineFoods/client/package.json
  lerna.json
  packages/airtable/package.json
  packages/altogic/package.json
  packages/core/package-lock.json
  packages/core/package.json
  packages/core/src/components/buttons/clone/index.spec.tsx
  packages/core/src/hooks/form/useCloneForm/useCloneForm.spec.tsx
  packages/core/src/hooks/form/useCloneForm/useCloneForm.ts
  packages/core/src/hooks/form/useDrawerForm/useDrawerForm.ts
  packages/core/src/hooks/form/useEditForm/useEditForm.ts
  packages/core/src/hooks/form/useForm.ts
  packages/core/src/hooks/form/useModalForm/useModalForm.ts
  packages/core/src/hooks/navigation/index.spec.tsx
  packages/core/src/hooks/navigation/index.ts
  packages/core/src/interfaces/resourceRouterParams.ts
  packages/demo-sidebar/package.json
  packages/graphql/package.json
  packages/hasura/package.json
  packages/nestjsx-crud/package.json
  packages/nextjs-router/package.json
  packages/nextjs-router/src/nextRouteComponent.tsx
  packages/react-location/package.json
  packages/react-location/src/resourceComponent.tsx
  packages/react-location/src/routerComponent.tsx
  packages/react-router/package.json
  packages/react-router/src/routeProvider.tsx
  packages/simple-rest/package.json
  packages/strapi-graphql/package.json
  packages/strapi/package.json
  packages/supabase/package.json
Labels: review-required, auto-merge

#1268 omit defaultFormValues prop on useModalForm
  packages/core/types/sunflower.d.ts
Labels: pr-ready, auto-merge

#1269 new blog added
  documentation/blog/2021-11-26-refine-vs-react-admin.md
  documentation/static/img/blog/2021-11-26-refine-vs-react-admin/admin_flow.png
  documentation/static/img/blog/2021-11-26-refine-vs-react-admin/project_setup.gif
  documentation/static/img/blog/2021-11-26-refine-vs-react-admin/refine_flow.png
Labels: pr-ready, review-required, auto-merge

#1275 update "eq" filter operator on strapi & strapi-graphql data providers
  examples/dataProvider/strapi/package.json
  packages/strapi-graphql/src/index.ts
  packages/strapi/src/dataProvider.ts
Labels: pr-ready, auto-merge
