Repository refinedev/refine, pull requests merged in 2022-04, with the labels that each got.

#1677 explanation of getDefaultSortOrder for initialSorter
  documentation/docs/ui-frameworks/antd/hooks/table/useTable.md
Labels: review-required, auto-merge

#1680 Add storybook example
  examples/storybook/.storybook/main.js
  examples/storybook/.storybook/preview.js
  examples/storybook/package.json
  examples/storybook/public/favicon.ico
  examples/storybook/public/index.html
  examples/storybook/public/manifest.json
  examples/storybook/src/App.tsx
  examples/storybook/src/index.tsx
  examples/storybook/src/interfaces/index.d.ts
  examples/storybook/src/react-app-env.d.ts
  examples/storybook/src/stories/crud/List.stories.tsx
  examples/storybook/src/stories/table/editable.stories.tsx
  examples/storybook/src/stories/table/search.stories.tsx
  examples/storybook/src/stories/table/table.stories.tsx
  examples/storybook/tsconfig.json
  packages/react-router-v6/src/index.ts
  packages/react-router-v6/src/routerComponent.tsx
Labels: pr-ready, auto-merge

#1678 Sorting sidebar elements
  documentation/sidebars.js
Labels: review-required, auto-merge

#1688 Add fallback for defaultValueQueryOptions on useSelect hook
  documentation/docs/core/hooks/useSelect.md
  documentation/docs/ui-frameworks/antd/hooks/field/useSelect.md
  packages/core/src/hooks/useSelect/index.spec.ts
  packages/core/src/hooks/useSelect/index.ts
Labels: review-required, auto-merge

#1695 Remove unnecessary 'prevFilters' param on 'unionFilters' function
  packages/core/src/definitions/table/index.spec.ts
  packages/core/src/definitions/table/index.ts
  packages/core/src/hooks/useTable/index.ts
Labels: pr-ready, auto-merge

#1698 useResource Document update
  documentation/docs/core/hooks/resource/useResource.md
Labels: review-required, auto-merge

#1696 useResource hook refactor
  documentation/docs/core/hooks/resource/useResource.md
  packages/antd/src/components/buttons/clone/index.tsx
  packages/antd/src/components/buttons/create/index.tsx
  packages/antd/src/components/buttons/delete/index.tsx
  packages/antd/src/components/buttons/edit/index.tsx
  packages/antd/src/components/buttons/list/index.tsx
  packages/antd/src/components/buttons/refresh/index.tsx
  packages/antd/src/components/buttons/show/index.tsx
  packages/core/src/contexts/resource/index.tsx
  packages/core/src/hooks/resource/useResource/index.spec.tsx
  packages/core/src/hooks/resource/useResource/index.ts
Labels: review-required, auto-merge

#1690 [Feature] Optional Invalidations for data hooks
  documentation/docs/core/hooks/data/useCreate.md
  documentation/docs/core/hooks/data/useCreateMany.md
  documentation/docs/core/hooks/data/useDelete.md
  documentation/docs/core/hooks/data/useDeleteMany.md
  documentation/docs/core/hooks/data/useUpdate.md
  documentation/docs/core/hooks/data/useUpdateMany.md
  documentation/docs/core/hooks/invalidate/useInvalidate.md
  documentation/docs/core/hooks/useForm.md
  documentation/docs/ui-frameworks/antd/components/buttons/delete.md
  documentation/docs/ui-frameworks/antd/hooks/form/useDrawerForm.md
  documentation/docs/ui-frameworks/antd/hooks/form/useForm.md
  documentation/docs/ui-frameworks/antd/hooks/form/useModalForm.md
  documentation/docs/ui-frameworks/antd/hooks/form/useStepsForm.md
  documentation/sidebars.js
  packages/antd/src/components/buttons/delete/index.tsx
  packages/core/src/definitions/helpers/queryKeys/index.ts
  packages/core/src/hooks/data/useCreate.ts
  packages/core/src/hooks/data/useCreateMany.ts
  packages/core/src/hooks/data/useDelete.ts
  packages/core/src/hooks/data/useDeleteMany.ts
  packages/core/src/hooks/data/useUpdate.ts
  packages/core/src/hooks/data/useUpdateMany.ts
  packages/core/src/hooks/form/useForm.ts
  packages/core/src/hooks/index.ts
  packages/core/src/hooks/invalidate/index.spec.tsx
  packages/core/src/hooks/invalidate/index.tsx
  packages/core/src/index.tsx
Labels: pr-ready, auto-merge

#1700 [Feature] Add variables support for useDelete and useDeleteMany hooks - RFC 7231
  documentation/docs/core/hooks/data/useDelete.md
  documentation/docs/core/hooks/data/useDeleteMany.md
  documentation/docs/core/hooks/data/useUpdate.md
  documentation/docs/core/providers/data-provider.md
  packages/core/src/contexts/data/IDataContext.ts
  packages/core/src/hooks/data/useDelete.ts
  packages/core/src/hooks/data/useDeleteMany.ts
Labels: pr-ready, auto-merge

#1702 Fix useShow id handle
  packages/core/src/hooks/show/useShow.spec.tsx
  packages/core/src/hooks/show/useShow.ts
Labels: review-required, auto-merge

#1715 [Bug] handle error state on useExport hook
  documentation/docs/core/hooks/import-export/useExport.md
  packages/core/src/hooks/export/index.spec.ts
  packages/core/src/hooks/export/index.ts
Labels: review-required, auto-merge

#1719 create useStepsForm for headless usage with react-hook-form
  packages/react-hook-form/jest.config.js
  packages/react-hook-form/package.json
  packages/react-hook-form/src/useStepsForm/index.spec.ts
  packages/react-hook-form/src/useStepsForm/index.ts
  packages/react-hook-form/test/dataMocks.ts
  packages/react-hook-form/test/index.tsx
  packages/react-hook-form/tsconfig.json
  packages/react-hook-form/tsconfig.test.json
Labels: review-required, auto-merge

#1717 Add react 18 support
  packages/antd/package.json
  packages/core/package.json
  packages/demo-sidebar/package.json
  packages/nextjs-router/package.json
  packages/react-hook-form/package.json
  packages/react-location/package.json
  packages/react-router-v6/package.json
  packages/react-router/package.json
  packages/react-table/package.json
  packages/strapi-v4/package.json
  packages/strapi/package.json
Labels: review-required, auto-merge, build examples

#1726 Fix useLayoutEffect issue for Next.js
  packages/antd/src/components/pages/error/index.tsx
  packages/core/src/components/pages/error/index.tsx
Labels: pr-ready, auto-merge

#1727 Fix Antd <FilterDropdown> can only be applied immediately
  packages/antd/src/components/table/components/filterDropdown/index.spec.tsx
  packages/antd/src/components/table/components/filterDropdown/index.tsx
Labels: pr-ready, review-required, auto-merge

#1728 resolve useForm mutation according to mutation mode
  packages/core/src/hooks/form/useForm.ts
Labels: review-required, auto-merge

#1732 create useModalForm hook for headless usage with react-hook-form
  packages/react-hook-form/package.json
  packages/react-hook-form/src/index.ts
  packages/react-hook-form/src/useForm/index.ts
  packages/react-hook-form/src/useModalForm/index.spec.ts
  packages/react-hook-form/src/useModalForm/index.ts
Labels: review-required, auto-merge

#1742 [Bug] Fix Ant Design form reset issue
  packages/antd/src/hooks/form/useForm.ts
Labels: review-required, auto-merge

#1743 [Snyk] Upgrade react-hook-form from 7.28.0 to 7.29.0
  documentation/package-lock.json
  documentation/package.json
Labels: review-required, auto-merge

#1741 Add "queryOptions" support for Forms hooks
  documentation/docs/core/hooks/useForm.md
  documentation/docs/guides-and-concepts/data-provider/appwrite.md
  documentation/docs/guides-and-concepts/multi-tenancy/appwrite.md
  documentation/docs/ui-frameworks/antd/hooks/form/useDrawerForm.md
  documentation/docs/ui-frameworks/antd/hooks/form/useForm.md
  documentation/docs/ui-frameworks/antd/hooks/form/useModalForm.md
  documentation/docs/ui-frameworks/antd/hooks/form/useStepsForm.md
  examples/dataProvider/appwrite/src/interfaces/index.d.ts
  examples/dataProvider/appwrite/src/pages/posts/create.tsx
  examples/dataProvider/appwrite/src/pages/posts/edit.tsx
  examples/dataProvider/appwrite/src/pages/posts/show.tsx
  examples/multi-tenancy/appwrite/package.json
  examples/multi-tenancy/appwrite/src/components/product/create.tsx
  examples/multi-tenancy/appwrite/src/components/product/edit.tsx
  examples/multi-tenancy/appwrite/src/components/product/item.tsx
  examples/multi-tenancy/appwrite/src/components/product/show.tsx
  examples/multi-tenancy/appwrite/src/components/select/index.tsx
  examples/multi-tenancy/appwrite/src/components/sider/index.tsx
  examples/multi-tenancy/appwrite/src/interfaces/index.d.ts
  examples/multi-tenancy/appwrite/src/pages/orders/list.tsx
  examples/multi-tenancy/appwrite/src/pages/products/list.tsx
  packages/antd/src/hooks/form/useDrawerForm/useDrawerForm.ts
  packages/antd/src/hooks/form/useForm.ts
  packages/antd/src/hooks/form/useModalForm/useModalForm.ts
  packages/antd/src/hooks/form/useStepsForm/useStepsForm.ts
  packages/core/src/hooks/form/useForm.ts
Labels: auto-merge

#1747 [Fix] Pagination does not take over filter conditions
  packages/core/src/definitions/table/index.spec.ts
  packages/core/src/definitions/table/index.ts
  packages/core/src/hooks/useTable/index.ts
Labels: review-required, auto-merge

#1750 Add FAQ page
  documentation/docs/faq.md
  documentation/sidebars.js
Labels: review-required, auto-merge

#1752 Fix props type and return types on react-hook-form hooks
  packages/react-hook-form/src/useModalForm/index.spec.ts
  packages/react-hook-form/src/useModalForm/index.ts
  packages/react-hook-form/src/useStepsForm/index.spec.ts
  packages/react-hook-form/src/useStepsForm/index.ts
Labels: review-required, auto-merge

#1751 inputProps return type and onChange prop fix
  documentation/docs/core/interfaces.md
  packages/core/src/hooks/import/index.tsx
Labels: review-required, auto-merge

#1749 [Feature] Add support for "id" prop in "useForm" hook
  documentation/docs/core/hooks/show/useShow.md
  documentation/docs/core/hooks/useForm.md
  documentation/docs/packages/react-hook-form.md
  documentation/docs/ui-frameworks/antd/hooks/form/useDrawerForm.md
  documentation/docs/ui-frameworks/antd/hooks/form/useForm.md
  documentation/docs/ui-frameworks/antd/hooks/form/useModalForm.md
  documentation/docs/ui-frameworks/antd/hooks/form/useStepsForm.md
  documentation/versioned_docs/version-2.xx.xx/api-references/hooks/show/useShow.md
  packages/core/src/hooks/form/useForm.spec.tsx
  packages/core/src/hooks/form/useForm.ts
  packages/core/src/hooks/show/useShow.spec.tsx
Labels: review-required, auto-merge

#1753 [Fix] Add support for "id" prop in Ant Design "useForm" hook
  packages/antd/src/hooks/form/useForm.ts
Labels: review-required, auto-merge

#1760 Mui login form
  examples/base/mui/public/index.html
  examples/base/mui/src/App.tsx
  packages/mui/package.json
  packages/mui/src/components/pages/login/index.tsx
  packages/mui/src/theme/index.ts
  packages/mui/src/theme/palette/darkPalette.ts
  packages/mui/src/theme/palette/lightPalette.ts
Labels: auto-merge

#1762 Mui fine foods login
  examples/fineFoods/admin/mui/public/images/bike-white.svg
  examples/fineFoods/admin/mui/public/images/bike.svg
  examples/fineFoods/admin/mui/public/images/daily-order.png
  examples/fineFoods/admin/mui/public/images/daily-revenue.png
  examples/fineFoods/admin/mui/public/images/default-order-img.png
  examples/fineFoods/admin/mui/public/images/default-store-img-lg.png
  examples/fineFoods/admin/mui/public/images/default-store-img.png
  examples/fineFoods/admin/mui/public/images/fine-foods-login.svg
  examples/fineFoods/admin/mui/public/images/fine-foods.svg
  examples/fineFoods/admin/mui/public/images/flags/de.svg
  examples/fineFoods/admin/mui/public/images/flags/en.svg
  examples/fineFoods/admin/mui/public/images/login-bg.png
  examples/fineFoods/admin/mui/public/images/map.png
  examples/fineFoods/admin/mui/public/images/new-orders.png
  examples/fineFoods/admin/mui/public/images/product-default-img.png
  examples/fineFoods/admin/mui/public/images/user-default-img.png
  examples/fineFoods/admin/mui/public/index.html
  examples/fineFoods/admin/mui/src/App.tsx
  examples/fineFoods/admin/mui/src/pages/login/index.tsx
Labels: review-required, auto-merge

#1759 Add Material UI finefoods example
  examples/fineFoods/admin/mui/.gitignore
  examples/fineFoods/admin/mui/package.json
  examples/fineFoods/admin/mui/public/favicon.ico
  examples/fineFoods/admin/mui/public/images/bike-white.svg
  examples/fineFoods/admin/mui/public/images/bike.svg
  examples/fineFoods/admin/mui/public/images/daily-order.png
  examples/fineFoods/admin/mui/public/images/daily-revenue.png
  examples/fineFoods/admin/mui/public/images/default-order-img.png
  examples/fineFoods/admin/mui/public/images/default-store-img-lg.png
  examples/fineFoods/admin/mui/public/images/default-store-img.png
  examples/fineFoods/admin/mui/public/images/fine-foods-login.svg
  examples/fineFoods/admin/mui/public/images/fine-foods.svg
  examples/fineFoods/admin/mui/public/images/flags/de.svg
  examples/fineFoods/admin/mui/public/images/flags/en.svg
  examples/fineFoods/admin/mui/public/images/login-bg.png
  examples/fineFoods/admin/mui/public/images/map.png
  examples/fineFoods/admin/mui/public/images/new-orders.png
  examples/fineFoods/admin/mui/public/images/product-default-img.png
  examples/fineFoods/admin/mui/public/images/user-default-img.png
  examples/fineFoods/admin/mui/public/index.html
  examples/fineFoods/admin/mui/public/locales/de.json
  examples/fineFoods/admin/mui/public/locales/en.json
  examples/fineFoods/admin/mui/public/manifest.json
  examples/fineFoods/admin/mui/src/App.tsx
  examples/fineFoods/admin/mui/src/authProvider.ts
  examples/fineFoods/admin/mui/src/i18n.ts
  examples/fineFoods/admin/mui/src/index.tsx
  examples/fineFoods/admin/mui/src/interfaces/index.d.ts
  examples/fineFoods/admin/mui/src/pages/login/index.tsx
  examples/fineFoods/admin/mui/src/pages/orders/index.ts
  examples/fineFoods/admin/mui/src/pages/orders/list.tsx
  examples/fineFoods/admin/mui/src/pages/orders/show.tsx
  examples/fineFoods/admin/mui/src/react-app-env.d.ts
  examples/fineFoods/admin/mui/tsconfig.json
Labels: review-required, auto-merge

#1768 Fix react-table return type
  packages/react-table/src/useTable/index.ts
Labels: review-required, auto-merge
