Repository refinedev/refine, pull requests merged in 2022-05, with the labels that each got.

#1777 new blog
  documentation/blog/2022-05-02-high-quality-free-resources.md
  documentation/static/img/blog/2022-05-02-high-quality-free-resources/antd.jpg
  documentation/static/img/blog/2022-05-02-high-quality-free-resources/auth0.jpg
  documentation/static/img/blog/2022-05-02-high-quality-free-resources/cerbos.jpg
  documentation/static/img/blog/2022-05-02-high-quality-free-resources/json-formatter.jpg
  documentation/static/img/blog/2022-05-02-high-quality-free-resources/lorem-ipsum.jpg
  documentation/static/img/blog/2022-05-02-high-quality-free-resources/lorem-picsum.jpg
  documentation/static/img/blog/2022-05-02-high-quality-free-resources/mui.jpg
  documentation/static/img/blog/2022-05-02-high-quality-free-resources/refine.jpg
  documentation/static/img/blog/2022-05-02-high-quality-free-resources/squoosh.jpg
  documentation/static/img/blog/2022-05-02-high-quality-free-resources/supabase.jpg
  documentation/static/img/blog/2022-05-02-high-quality-free-resources/tailwind.jpg
Labels: auto-merge

#1767 [Doc] Add permify example
  documentation/docs/core/providers/accessControl-provider.md
  documentation/docs/examples/access-control/permify.md
  documentation/sidebars.js
Labels: review-required, auto-merge

#1773 [Blog] The Advantages and Disadvantages of Working on Open Source Projects
  documentation/blog/2022-04-29-open-source-adv-disadv.md
Labels: review-required, auto-merge

#1774 Refine full stack app blog
  documentation/blog/2022-04-29-create-full-stack-app.md
  documentation/static/img/blog/2022-04-29-create-full-stack-app/client_home.png
  documentation/static/img/blog/2022-04-29-create-full-stack-app/client_menu.png
  documentation/static/img/blog/2022-04-29-create-full-stack-app/create.gif
  documentation/static/img/blog/2022-04-29-create-full-stack-app/dashboard.png
  documentation/static/img/blog/2022-04-29-create-full-stack-app/first.png
  documentation/static/img/blog/2022-04-29-create-full-stack-app/products.png
  documentation/static/img/blog/2022-04-29-create-full-stack-app/reviews.png
Labels: review-required, auto-merge

#1775 Add blog post related to ui libraries and frameworks
  documentation/blog/2022-04-29-top-react-component-libraries-and-frameworks-every-developer-should-know.md
  documentation/static/img/blog/2022-04-29-top-react-component-libraries-and-frameworks-every-developer-should-know/antd.png
  documentation/static/img/blog/2022-04-29-top-react-component-libraries-and-frameworks-every-developer-should-know/chakra.png
  documentation/static/img/blog/2022-04-29-top-react-component-libraries-and-frameworks-every-developer-should-know/mantine.png
  documentation/static/img/blog/2022-04-29-top-react-component-libraries-and-frameworks-every-developer-should-know/mui.png
  documentation/static/img/blog/2022-04-29-top-react-component-libraries-and-frameworks-every-developer-should-know/refine.png
  documentation/static/img/blog/2022-04-29-top-react-component-libraries-and-frameworks-every-developer-should-know/storybook.png
Labels: auto-merge

#1782 Add headless cms blog post.
  documentation/blog/2022-05-05-open-source-headless-cms.md
  documentation/static/img/blog/2022-05-05-open-source-headless-cms/appwrite.jpg
  documentation/static/img/blog/2022-05-05-open-source-headless-cms/directus.jpg
  documentation/static/img/blog/2022-05-05-open-source-headless-cms/keystone.jpg
  documentation/static/img/blog/2022-05-05-open-source-headless-cms/netlify.jpg
  documentation/static/img/blog/2022-05-05-open-source-headless-cms/refine.jpg
  documentation/static/img/blog/2022-05-05-open-source-headless-cms/strapi.jpg
Labels: review-required, auto-merge

#1783 [Bug] Fix setWarnWhen on @pankod/refine-react-hook-form
  packages/react-hook-form/src/useForm/index.ts
Labels: auto-merge

#1731 refine-real-world-example
  examples/real-world-example/package.json
  examples/real-world-example/public/favicon.ico
  examples/real-world-example/public/index.html
  examples/real-world-example/src/App.tsx
  examples/real-world-example/src/authProvider.ts
  examples/real-world-example/src/components/Error.tsx
  examples/real-world-example/src/components/Footer.tsx
  examples/real-world-example/src/components/Header.tsx
  examples/real-world-example/src/components/Layout.tsx
  examples/real-world-example/src/components/Pagination.tsx
  examples/real-world-example/src/components/article/index.tsx
  examples/real-world-example/src/components/home/Banner.tsx
  examples/real-world-example/src/components/home/index.ts
  examples/real-world-example/src/components/index.ts
  examples/real-world-example/src/components/profile/ProfileNav.tsx
  examples/real-world-example/src/components/profile/UserInfo.tsx
  examples/real-world-example/src/components/profile/index.ts
  examples/real-world-example/src/components/tag/index.tsx
  examples/real-world-example/src/constants.ts
  examples/real-world-example/src/dataProvider.ts
  examples/real-world-example/src/index.tsx
  examples/real-world-example/src/interfaces/index.d.ts
  examples/real-world-example/src/meta.json
  examples/real-world-example/src/pages/article/index.tsx
  examples/real-world-example/src/pages/auth/LoginPage.tsx
  examples/real-world-example/src/pages/auth/RegisterPage.tsx
  examples/real-world-example/src/pages/auth/index.tsx
  examples/real-world-example/src/pages/editor/create.tsx
  examples/real-world-example/src/pages/editor/edit.tsx
  examples/real-world-example/src/pages/editor/index.tsx
  examples/real-world-example/src/pages/home/index.tsx
  examples/real-world-example/src/pages/profile/index.tsx
  examples/real-world-example/src/pages/settings/index.tsx
  examples/real-world-example/src/react-app-env.d.ts
  examples/real-world-example/src/reportWebVitals.ts
  examples/real-world-example/src/setupTests.ts
  examples/real-world-example/tsconfig.json
  packages/core/src/contexts/auth/index.tsx
  packages/core/src/hooks/auth/useGetIdentity/index.ts
  packages/core/src/hooks/auth/usePermissions/index.ts
Labels: review-required, auto-merge

#1787 Add hash router support for react-router-v6
  packages/react-router-v6/src/index.ts
  packages/react-router-v6/src/routerComponent.tsx
Labels: review-required, auto-merge

#1766 mui table examples
  examples/table/mui/.gitignore
  examples/table/mui/package.json
  examples/table/mui/public/favicon.ico
  examples/table/mui/public/index.html
  examples/table/mui/public/manifest.json
  examples/table/mui/src/App.tsx
  examples/table/mui/src/index.tsx
  examples/table/mui/src/interfaces/index.d.ts
  examples/table/mui/src/pages/dataGrid/basicDataGrid.tsx
  examples/table/mui/src/pages/dataGrid/index.ts
  examples/table/mui/src/pages/table/index.tsx
  examples/table/mui/src/pages/table/list.tsx
  examples/table/mui/src/react-app-env.d.ts
  examples/table/mui/src/react-table-config.d.ts
  examples/table/mui/tsconfig.json
  packages/mui/package.json
Labels: review-required, auto-merge

#1765 Add reviews page on Material UI FineFoods demo
  examples/fineFoods/admin/mui/public/index.html
  examples/fineFoods/admin/mui/src/App.tsx
  examples/fineFoods/admin/mui/src/index.tsx
  examples/fineFoods/admin/mui/src/pages/reviews/index.ts
  examples/fineFoods/admin/mui/src/pages/reviews/list.tsx
Labels: review-required, auto-merge

#1784 Mui finefoods users resource
  examples/fineFoods/admin/mui/src/App.tsx
  examples/fineFoods/admin/mui/src/interfaces/index.d.ts
  examples/fineFoods/admin/mui/src/pages/users/index.ts
  examples/fineFoods/admin/mui/src/pages/users/list.tsx
  examples/fineFoods/admin/mui/src/pages/users/show.tsx
Labels: review-required, auto-merge

#1797 [Bug] Fix error handling on nhost data provider
  examples/dataProvider/nhost/src/App.tsx
  packages/nhost/src/index.ts
Labels: pr-ready, auto-merge

#1764 Mui fine foods products
  examples/fineFoods/admin/mui/src/App.tsx
  examples/fineFoods/admin/mui/src/components/index.ts
  examples/fineFoods/admin/mui/src/components/product/categoryFilter.tsx
  examples/fineFoods/admin/mui/src/components/product/create.tsx
  examples/fineFoods/admin/mui/src/components/product/edit.tsx
  examples/fineFoods/admin/mui/src/components/product/index.tsx
  examples/fineFoods/admin/mui/src/components/product/item.tsx
  examples/fineFoods/admin/mui/src/pages/products/index.tsx
  examples/fineFoods/admin/mui/src/pages/products/list.tsx
  packages/mui/src/components/crud/edit/index.tsx
  packages/mui/src/components/layout/header/styled.tsx
Labels: pr-ready, auto-merge

#1799 [Improvement] Move getDefaultFilter and getDefaultSorter to core package
  documentation/docs/core/interfaces.md
  documentation/docs/ui-frameworks/antd/components/filter-dropdown.md
  documentation/docs/ui-frameworks/antd/hooks/table/useTable.md
  examples/base/src/pages/posts/list.tsx
  examples/dataProvider/hasura/src/pages/posts/list.tsx
  examples/dataProvider/multiple/src/pages/posts/list.tsx
  examples/dataProvider/nhost/src/pages/posts/list.tsx
  examples/dataProvider/strapi/src/pages/posts/list.tsx
  examples/fineFoods/admin/src/pages/orders/list.tsx
  examples/fineFoods/admin/src/pages/products/list.tsx
  examples/multi-level-menu/src/pages/posts/list.tsx
  examples/table/useTable/src/pages/posts/list.tsx
  examples/vite/src/pages/posts/list.tsx
  packages/antd/src/definitions/table/index.ts
  packages/core/src/contexts/data/IDataContext.ts
  packages/core/src/definitions/table/index.spec.ts
  packages/core/src/definitions/table/index.ts
  packages/core/src/index.tsx
Labels: auto-merge

#1803 Add saveButtonProps for @pankod/refine-react-hook-form
  documentation/docs/packages/react-hook-form.md
  packages/react-hook-form/src/useForm/index.ts
  packages/react-hook-form/src/useModalForm/index.ts
Labels: review-required, auto-merge

#1789 Mui finefoods dashboard page
  examples/fineFoods/admin/mui/package.json
  examples/fineFoods/admin/mui/src/App.tsx
  examples/fineFoods/admin/mui/src/components/dashboard/chartTooltip/index.tsx
  examples/fineFoods/admin/mui/src/components/dashboard/dailyOrders/index.tsx
  examples/fineFoods/admin/mui/src/components/dashboard/dailyRevenue/index.tsx
  examples/fineFoods/admin/mui/src/components/dashboard/deliveryMap/index.tsx
  examples/fineFoods/admin/mui/src/components/dashboard/index.ts
  examples/fineFoods/admin/mui/src/components/dashboard/newCustomers/index.tsx
  examples/fineFoods/admin/mui/src/components/dashboard/orderTimeline/index.tsx
  examples/fineFoods/admin/mui/src/components/dashboard/recentOrders/index.tsx
  examples/fineFoods/admin/mui/src/components/dashboard/trendingMenu/index.tsx
  examples/fineFoods/admin/mui/src/index.tsx
  examples/fineFoods/admin/mui/src/pages/dashboard/index.tsx
  examples/fineFoods/admin/mui/src/pages/orders/list.tsx
  examples/fineFoods/admin/mui/src/pages/orders/show.tsx
  examples/fineFoods/admin/src/components/dashboard/recentOrders/index.tsx
  packages/mui/src/index.tsx
Labels: pr-ready, auto-merge

#1796 Mui - fine foods example stores page created
  examples/fineFoods/admin/mui/src/App.tsx
  examples/fineFoods/admin/mui/src/components/product/item.tsx
  examples/fineFoods/admin/mui/src/components/store/index.tsx
  examples/fineFoods/admin/mui/src/components/store/storeProducts.tsx
  examples/fineFoods/admin/mui/src/pages/stores/create.tsx
  examples/fineFoods/admin/mui/src/pages/stores/edit.tsx
  examples/fineFoods/admin/mui/src/pages/stores/index.tsx
  examples/fineFoods/admin/mui/src/pages/stores/list.tsx
Labels: pr-ready, auto-merge

#1811 [Bug] Fix syncWithLocation reset issue on useTable hook
  packages/core/src/hooks/useTable/index.ts
Labels: auto-merge

#1808 Mui fine foods stores page reviews resolved
  examples/fineFoods/admin/mui/public/locales/de.json
  examples/fineFoods/admin/mui/public/locales/en.json
  examples/fineFoods/admin/mui/src/components/product/create.tsx
  examples/fineFoods/admin/mui/src/components/product/edit.tsx
  examples/fineFoods/admin/mui/src/components/product/item.tsx
  examples/fineFoods/admin/mui/src/components/store/storeProducts.tsx
  examples/fineFoods/admin/mui/src/pages/products/list.tsx
  examples/fineFoods/admin/mui/src/pages/stores/create.tsx
  examples/fineFoods/admin/mui/src/pages/stores/edit.tsx
  packages/mui/src/components/crud/create/index.tsx
  packages/mui/src/components/crud/edit/index.tsx
  packages/mui/src/components/crud/list/index.tsx
  packages/mui/src/components/crud/show/index.tsx
Labels: review-required, auto-merge

#1795 Mui fine food couriers page
  examples/fineFoods/admin/mui/package.json
  examples/fineFoods/admin/mui/public/locales/de.json
  examples/fineFoods/admin/mui/public/locales/en.json
  examples/fineFoods/admin/mui/src/App.tsx
  examples/fineFoods/admin/mui/src/pages/couriers/create.tsx
  examples/fineFoods/admin/mui/src/pages/couriers/edit.tsx
  examples/fineFoods/admin/mui/src/pages/couriers/index.ts
  examples/fineFoods/admin/mui/src/pages/couriers/list.tsx
  examples/fineFoods/admin/mui/src/pages/couriers/show.tsx
  examples/fineFoods/admin/mui/src/pages/reviews/list.tsx
  packages/mui/src/hooks/useDataGrid/index.ts
Labels: pr-ready, auto-merge

#1818 [Bug] Fix id decode for CanAccess component on react-router-v6 and react-lo…
  packages/react-location/src/resourceComponent.tsx
  packages/react-router-v6/src/routeProvider.tsx
Labels: review-required, auto-merge

#1824 Make links more accessible for Next.js integration
  examples/blog/ecommerce/next.config.js
  examples/i18n/nextjs/next.config.js
  examples/refine-next/next.config.js
  packages/antd/src/components/buttons/clone/index.tsx
  packages/antd/src/components/buttons/create/index.tsx
  packages/antd/src/components/buttons/edit/index.tsx
  packages/antd/src/components/buttons/list/index.tsx
  packages/antd/src/components/buttons/show/index.tsx
  packages/antd/src/components/layout/sider/index.tsx
  packages/antd/src/hooks/table/useTable/paginationLink.tsx
Labels: review-required, auto-merge

#1827 [Bug] Fix Antd form initialValues issue on useDrawerForm, useModalForm
  packages/antd/src/hooks/form/useDrawerForm/useDrawerForm.ts
  packages/antd/src/hooks/form/useModalForm/useModalForm.ts
  packages/antd/src/hooks/form/useStepsForm/useStepsForm.ts
Labels: review-required, auto-merge

#1834 Improvement Ant Design calendar example
  documentation/docs/examples/calendar.md
  documentation/sidebars.js
  examples/calendar/package.json
  examples/calendar/src/App.tsx
  examples/calendar/src/interfaces/index.d.ts
  examples/calendar/src/pages/calendar/index.tsx
Labels: review-required, auto-merge

#1831 Theme Fixes
  examples/fineFoods/admin/mui/public/locales/de.json
  examples/fineFoods/admin/mui/public/locales/en.json
  examples/fineFoods/admin/mui/src/App.tsx
  examples/fineFoods/admin/mui/src/components/dashboard/orderTimeline/index.tsx
  examples/fineFoods/admin/mui/src/components/product/create.tsx
  examples/fineFoods/admin/mui/src/components/product/edit.tsx
  examples/fineFoods/admin/mui/src/interfaces/index.d.ts
  examples/fineFoods/admin/mui/src/interfaces/theme.d.ts
  examples/fineFoods/admin/mui/src/pages/couriers/list.tsx
  examples/fineFoods/admin/mui/src/pages/products/list.tsx
  examples/fineFoods/admin/mui/src/pages/reviews/list.tsx
  examples/fineFoods/admin/mui/src/pages/stores/list.tsx
  examples/fineFoods/admin/mui/src/pages/users/list.tsx
  examples/fineFoods/admin/mui/src/theme.ts
  packages/mui/src/components/fields/boolean/index.tsx
  packages/mui/src/components/fields/date/index.tsx
  packages/mui/src/components/fields/email/index.tsx
  packages/mui/src/components/fields/number/index.tsx
  packages/mui/src/components/fields/text/index.tsx
  packages/mui/src/components/fields/url/index.tsx
  packages/mui/src/theme/index.ts
Labels: pr-ready, auto-merge

#1838 Fix hardcoded color
  examples/fineFoods/admin/mui/src/components/dashboard/orderTimeline/index.tsx
Labels: pr-ready, review-required, auto-merge

#1837 page props types updated with IResourceComponentProps
  examples/fineFoods/admin/mui/src/pages/couriers/show.tsx
  examples/fineFoods/admin/mui/src/pages/stores/edit.tsx
  examples/fineFoods/admin/mui/src/pages/stores/list.tsx
  examples/fineFoods/admin/mui/src/pages/users/list.tsx
  examples/fineFoods/admin/mui/src/pages/users/show.tsx
Labels: pr-ready, auto-merge

#1829 categories page table init
  examples/fineFoods/admin/mui/package.json
  examples/fineFoods/admin/mui/src/App.tsx
  examples/fineFoods/admin/mui/src/components/product/create.tsx
  examples/fineFoods/admin/mui/src/components/product/edit.tsx
  examples/fineFoods/admin/mui/src/pages/categories/index.ts
  examples/fineFoods/admin/mui/src/pages/categories/list.tsx
  examples/fineFoods/admin/mui/src/react-table-config.d.ts
Labels: auto-merge

#1846 [Snyk] Upgrade react-player from 2.9.0 to 2.10.1
  documentation/package-lock.json
  documentation/package.json
Labels: review-required, auto-merge

#1849 Test PR for CodeSandbox
  .codesandbox/ci.json
  .github/workflows/pull-request-closed.yml
  .github/workflows/pull-request.yml
  package.json
Labels: review-required, auto-merge

#1851 Add changeset
  .changeset/README.md
  .changeset/config.json
  package-lock.json
  package.json
Labels: review-required, auto-merge

#1852 feat(commitlint): Add commitlint
  .github/workflows/pull-request.yml
  .gitignore
  .husky/commit-msg
  .husky/pre-commit
  README.md
  commitlint.config.js
  package-lock.json
  package.json
Labels: auto-merge

#1854 fix(ci): fork pr's status check failures
  .github/workflows/automerge.yml
  .github/workflows/pull-request.yml
  .github/workflows/reviewer-lottery.yml
Labels: review-required, auto-merge

#1855 feat(surge): add surge preview support for pr docs
  .github/workflows/pull-request-closed.yml
  .github/workflows/pull-request-doc.yml
  documentation/README.md
Labels: review-required, auto-merge

#1850 styles(notistack): made compatible with Theme
  .changeset/chilled-steaks-cheat.md
  examples/fineFoods/admin/mui/src/App.tsx
  examples/fineFoods/admin/mui/src/contexts/index.tsx
  examples/fineFoods/admin/mui/src/index.tsx
  packages/mui/src/components/circularDeterminate/index.tsx
  packages/mui/src/providers/notificationProvider/index.tsx
Labels: pr-ready, auto-merge
