Repository refinedev/refine, pull requests merged in 2022-01, with the labels that each got.

#1398 handle not supporeted filter operators on data providers
  packages/altogic/src/index.ts
  packages/appwrite/src/index.ts
  packages/appwrite/test/getList/index.spec.ts
  packages/simple-rest/src/index.ts
  packages/supabase/src/index.ts
  packages/supabase/test/getList/index.spec.ts
Labels: review-required, auto-merge

#1401 fix buttons resourceName prop issue
  packages/core/src/components/buttons/clone/index.tsx
  packages/core/src/components/buttons/create/index.tsx
  packages/core/src/components/buttons/edit/index.tsx
  packages/core/src/components/buttons/list/index.tsx
  packages/core/src/components/buttons/show/index.tsx
  packages/core/src/hooks/resource/useResourceWithRoute/index.ts
Labels: review-required, auto-merge

#1287 Improvement Contributing Guide
  documentation/docs/contributing.md
  documentation/versioned_docs/version-2.xx.xx/contributing.md
  lerna.json
  package.json
  packages/codemod/package-lock.json
Labels: review-required, auto-merge

#1407 cake house example code added
  documentation/docs/examples/multi-tenant/multi-tenant-example.md
  documentation/sidebars.js
  documentation/versioned_docs/version-2.xx.xx/examples/multi-tenant/multi-tenant-example.md
  documentation/versioned_sidebars/version-2.xx.xx-sidebars.json
  examples/multi-tenant/cakeHouse/package.json
  examples/multi-tenant/cakeHouse/public/favicon.ico
  examples/multi-tenant/cakeHouse/public/index.html
  examples/multi-tenant/cakeHouse/public/refine.svg
  examples/multi-tenant/cakeHouse/src/App.tsx
  examples/multi-tenant/cakeHouse/src/authProvider.ts
  examples/multi-tenant/cakeHouse/src/components/product/create.tsx
  examples/multi-tenant/cakeHouse/src/components/product/edit.tsx
  examples/multi-tenant/cakeHouse/src/components/product/index.ts
  examples/multi-tenant/cakeHouse/src/components/product/item.tsx
  examples/multi-tenant/cakeHouse/src/components/product/show.tsx
  examples/multi-tenant/cakeHouse/src/components/select/index.tsx
  examples/multi-tenant/cakeHouse/src/components/sider/index.tsx
  examples/multi-tenant/cakeHouse/src/components/sider/styles.ts
  examples/multi-tenant/cakeHouse/src/context/store/index.tsx
  examples/multi-tenant/cakeHouse/src/index.tsx
  examples/multi-tenant/cakeHouse/src/interfaces/index.d.ts
  examples/multi-tenant/cakeHouse/src/meta.json
  examples/multi-tenant/cakeHouse/src/pages/login/index.tsx
  examples/multi-tenant/cakeHouse/src/pages/login/styles.css
  examples/multi-tenant/cakeHouse/src/pages/orders/create.tsx
  examples/multi-tenant/cakeHouse/src/pages/orders/edit.tsx
  examples/multi-tenant/cakeHouse/src/pages/orders/index.tsx
  examples/multi-tenant/cakeHouse/src/pages/orders/list.tsx
  examples/multi-tenant/cakeHouse/src/pages/products/index.tsx
  examples/multi-tenant/cakeHouse/src/pages/products/list.tsx
  examples/multi-tenant/cakeHouse/src/react-app-env.d.ts
  examples/multi-tenant/cakeHouse/src/reportWebVitals.ts
  examples/multi-tenant/cakeHouse/src/setupTests.ts
  examples/multi-tenant/cakeHouse/src/utility/appwriteClient.ts
  examples/multi-tenant/cakeHouse/src/utility/index.ts
  examples/multi-tenant/cakeHouse/src/utility/normalize.ts
  examples/multi-tenant/cakeHouse/tsconfig.json
Labels: pr-ready, review-required, auto-merge

#1412 Typo fix - Releations to Relations in versioned docs
  documentation/versioned_docs/version-2.xx.xx/guides-and-concepts/data-provider/strapi-v4.md
Labels: review-required, auto-merge

#1413 Multi tenant guide
  documentation/docs/guides-and-concepts/multi-tenant.md
  documentation/sidebars.js
  documentation/static/img/guides-and-concepts/multi-tenant/collections.png
  documentation/static/img/guides-and-concepts/multi-tenant/create.gif
  documentation/static/img/guides-and-concepts/multi-tenant/sider.png
  documentation/static/img/guides-and-concepts/multi-tenant/store-filter.gif
  documentation/versioned_docs/version-2.xx.xx/guides-and-concepts/multi-tenant.md
  documentation/versioned_sidebars/version-2.xx.xx-sidebars.json
Labels: pr-ready, review-required, auto-merge

#1414 unnecessary used any type fixed
  examples/multi-tenant/cakeHouse/src/components/product/create.tsx
  examples/multi-tenant/cakeHouse/src/pages/orders/create.tsx
  examples/multi-tenant/cakeHouse/src/pages/products/list.tsx
Labels: review-required, auto-merge

#1415 added announcementBar to docs
  documentation/docusaurus.config.js
  documentation/src/css/custom.css
Labels: review-required, auto-merge

#1416 announcementBar edited
  documentation/docusaurus.config.js
Labels: review-required, auto-merge

#1418 undefined image issue fixed
  examples/multi-tenant/cakeHouse/public/error.png
  examples/multi-tenant/cakeHouse/src/components/product/edit.tsx
  examples/multi-tenant/cakeHouse/src/components/product/item.tsx
  examples/multi-tenant/cakeHouse/src/pages/orders/list.tsx
Labels: review-required, auto-merge

#1408 Headless Notification with notificationProvider
  examples/tailwind/package.json
  examples/tailwind/src/App.tsx
  examples/tailwind/src/components/undoableNotification.tsx
  examples/tailwind/src/notificationProvider.tsx
  examples/tailwind/src/pages/posts/create.tsx
  examples/tailwind/src/pages/posts/edit.tsx
  examples/tailwind/src/pages/posts/list.tsx
  packages/antd/.babelrc
  packages/antd/src/components/undoableNotification/index.spec.tsx
  packages/antd/src/components/undoableNotification/index.tsx
  packages/antd/src/index.tsx
  packages/antd/src/providers/index.ts
  packages/antd/src/providers/notificationProvider/index.spec.tsx
  packages/antd/src/providers/notificationProvider/index.tsx
  packages/antd/test/index.tsx
  packages/core/src/components/containers/refine/index.tsx
  packages/core/src/components/notification/components/index.ts
  packages/core/src/components/notification/components/notificationProgress/index.spec.tsx
  packages/core/src/components/notification/components/notificationProgress/index.tsx
  packages/core/src/components/notification/index.spec.tsx
  packages/core/src/components/notification/index.tsx
  packages/core/src/contexts/notificationProvider/INotificationProvider.ts
  packages/core/src/contexts/notificationProvider/index.tsx
  packages/core/src/definitions/helpers/handleNotification/index.spec.tsx
  packages/core/src/definitions/helpers/handleNotification/index.ts
  packages/core/src/definitions/helpers/index.ts
  packages/core/src/hooks/auth/useLogin/index.ts
  packages/core/src/hooks/auth/useLogout/index.ts
  packages/core/src/hooks/data/useCreate.ts
  packages/core/src/hooks/data/useCreateMany.ts
  packages/core/src/hooks/data/useCustom.ts
  packages/core/src/hooks/data/useDelete.ts
  packages/core/src/hooks/data/useDeleteMany.ts
  packages/core/src/hooks/data/useList.ts
  packages/core/src/hooks/data/useMany.ts
  packages/core/src/hooks/data/useOne.ts
  packages/core/src/hooks/data/useUpdate.ts
  packages/core/src/hooks/data/useUpdateMany.ts
  packages/core/src/hooks/import/index.tsx
  packages/core/src/hooks/notification/index.ts
  packages/core/src/hooks/notification/useHandleNotification/index.spec.tsx
  packages/core/src/hooks/notification/useHandleNotification/index.ts
  packages/core/src/hooks/notification/useNotification/index.ts
  packages/core/src/index.tsx
  packages/core/src/interfaces/index.ts
  packages/core/src/interfaces/successErrorNotification.ts
  packages/core/test/index.tsx
Labels: review-required, auto-merge

#1419 docs link edited
  documentation/docusaurus.config.js
Labels: review-required, auto-merge

#1421 Headless Layout
  examples/tailwind/src/App.tsx
  examples/tailwind/src/pages/posts/show.tsx
  packages/antd/src/components/index.ts
  packages/antd/src/components/layout/header/index.spec.tsx
  packages/antd/src/components/layout/header/index.tsx
  packages/antd/src/components/layout/index.spec.tsx
  packages/antd/src/components/layout/index.tsx
  packages/antd/src/components/layout/sider/index.spec.tsx
  packages/antd/src/components/layout/sider/index.tsx
  packages/antd/src/components/layout/sider/styles.ts
  packages/antd/src/components/layout/title/index.tsx
  packages/antd/test/index.tsx
  packages/core/src/components/layoutWrapper/components/footer/index.tsx
  packages/core/src/components/layoutWrapper/components/index.ts
  packages/core/src/components/layoutWrapper/components/offLayoutArea/index.tsx
  packages/core/src/components/layoutWrapper/defaultLayout/index.tsx
  packages/core/src/components/layoutWrapper/index.spec.tsx
  packages/core/src/components/layoutWrapper/index.tsx
  packages/core/src/contexts/refine/index.tsx
  packages/core/src/hooks/auth/index.ts
  packages/core/src/hooks/auth/useIsExistAuthentication.ts
Labels: pr-ready, review-required, auto-merge

#1307 [Bug] Layout re-render on route change
  examples/accessControl/casbin/src/App.tsx
  examples/accessControl/casbin/src/components/header.tsx
  examples/accessControl/cerbos/src/App.tsx
  examples/accessControl/cerbos/src/components/header.tsx
  packages/react-router/src/routeProvider.tsx
Labels: review-required, auto-merge

#1424 handle querystring undefined case on useLogin hook
  packages/core/src/hooks/auth/useLogin/index.ts
Labels: review-required, auto-merge

#1420 Headless useImport
  examples/importExport/package.json
  examples/importExport/src/App.tsx
  examples/importExport/src/pages/posts/create.tsx
  examples/importExport/src/pages/posts/edit.tsx
  examples/importExport/src/pages/posts/list.tsx
  examples/importExport/src/pages/posts/show.tsx
  examples/tailwind/src/pages/posts/list.tsx
  packages/antd/src/hooks/import/index.spec.ts
  packages/antd/src/hooks/import/index.tsx
  packages/antd/src/hooks/index.ts
  packages/core/src/components/buttons/import/index.spec.tsx
  packages/core/src/hooks/data/index.ts
  packages/core/src/hooks/import/index.spec.tsx
  packages/core/src/hooks/import/index.tsx
  packages/core/src/index.tsx
Labels: review-required, auto-merge

#1425 move field components to antd package
  examples/base/src/App.tsx
  examples/importExport/src/App.tsx
  examples/table/useEditableTable/src/App.tsx
  examples/tailwind/src/App.tsx
  packages/antd/src/components/fields/boolean/index.spec.tsx
  packages/antd/src/components/fields/boolean/index.tsx
  packages/antd/src/components/fields/date/index.spec.tsx
  packages/antd/src/components/fields/date/index.tsx
  packages/antd/src/components/fields/email/index.spec.tsx
  packages/antd/src/components/fields/email/index.tsx
  packages/antd/src/components/fields/file/index.spec.tsx
  packages/antd/src/components/fields/file/index.tsx
  packages/antd/src/components/fields/image/index.spec.tsx
  packages/antd/src/components/fields/image/index.tsx
  packages/antd/src/components/fields/index.ts
  packages/antd/src/components/fields/markdown/index.spec.tsx
  packages/antd/src/components/fields/markdown/index.tsx
  packages/antd/src/components/fields/number/index.spec.tsx
  packages/antd/src/components/fields/number/index.tsx
  packages/antd/src/components/fields/tag/index.spec.tsx
  packages/antd/src/components/fields/tag/index.tsx
  packages/antd/src/components/fields/text/index.spec.tsx
  packages/antd/src/components/fields/text/index.tsx
  packages/antd/src/components/fields/url/index.spec.tsx
  packages/antd/src/components/fields/url/index.tsx
  packages/antd/src/components/index.ts
  packages/antd/src/hooks/form/useModalForm/useModalForm.ts
  packages/antd/src/hooks/form/useStepsForm/useStepsForm.ts
  packages/antd/src/index.tsx
  packages/antd/src/interfaces/field.ts
  packages/antd/src/interfaces/index.ts
  packages/antd/types/sunflower.d.ts
  packages/core/package.json
  packages/core/src/assets/styles/custom-theme.less
  packages/core/src/assets/styles/styles.min.css
  packages/core/src/components/index.ts
  packages/core/src/index.tsx
  packages/core/src/interfaces/index.ts
  packages/core/src/interfaces/match.ts
  packages/core/tsdx.config.js
Labels: review-required, auto-merge

#1435 fix useMenu selected key issue
  packages/core/src/hooks/resource/useMenu/index.tsx
Labels: auto-merge

#1437 Fix useTable returning FormInstance as formProps
  packages/core/src/hooks/table/useTable/useTable.ts
Labels: review-required, auto-merge

#1443 Handle custom route option on @pankod/refine-nextjs-router
  examples/refine-next/next-env.d.ts
  packages/nextjs-router/src/nextRouteComponent.tsx
Labels: review-required, auto-merge

#1454 Add Refine React Table Unit Tests
  examples/tailwind/src/pages/posts/list.tsx
  packages/antd/src/hooks/table/useTable/useTable.ts
  packages/core/src/hooks/useTable/index.ts
  packages/react-table/jest.config.js
  packages/react-table/package.json
  packages/react-table/src/useTable/index.spec.ts
  packages/react-table/src/useTable/index.ts
  packages/react-table/test/dataMocks.ts
  packages/react-table/test/index.tsx
  packages/react-table/tsconfig.json
  packages/react-table/tsconfig.test.json
Labels: review-required, auto-merge

#1456 refine-ably import packages uptade
  documentation/docs/guides-and-concepts/real-time.md
Labels: review-required, auto-merge

#1457 base64 import packages update
  documentation/docs/guides-and-concepts/upload/base64-upload.md
Labels: review-required, auto-merge

#1459 refine-search import packages update
  documentation/docs/guides-and-concepts/search/search.md
Labels: review-required, auto-merge

#1460 table-search import packages update
  documentation/docs/guides-and-concepts/search/table-search.md
Labels: review-required, auto-merge

#1463 csv-import docs import packages update
  documentation/docs/guides-and-concepts/import-export/csv-import.md
Labels: review-required, auto-merge

#1465 custom-validation import packages update
  documentation/docs/guides-and-concepts/forms/custom-form-validation.md
Labels: review-required, auto-merge

#1464 csv-export docs import packages update
  documentation/docs/guides-and-concepts/import-export/csv-export.md
Labels: review-required, auto-merge

#1466 ethereum-signin import packages update
  documentation/docs/guides-and-concepts/web3/ethereum-signin.md
Labels: review-required, auto-merge

#1468 appwrite multi-tenancy import packages update
  documentation/docs/guides-and-concepts/multi-tenancy/appwrite.md
Labels: review-required, auto-merge

#1469 strapi multi-tenancy import packages update
  documentation/docs/guides-and-concepts/multi-tenancy/strapi.md
Labels: review-required, auto-merge

#1470 mutation-mode import package update
  documentation/docs/guides-and-concepts/mutation-mode.md
Labels: review-required, auto-merge

#1471 custom-layout import packages update
  documentation/docs/guides-and-concepts/custom-layout.md
Labels: review-required, auto-merge

#1472 custom-pages import packages update
  documentation/docs/guides-and-concepts/custom-pages.md
Labels: review-required, auto-merge

#1473 theme-docs import package update
  documentation/docs/guides-and-concepts/theme.md
Labels: review-required, auto-merge

#1474 auth0 import packages update
  documentation/docs/guides-and-concepts/auth/auth0.md
Labels: review-required, auto-merge

#1475 refine-tutorial-example import packages update
  documentation/docs/tutorial.md
Labels: review-required, auto-merge

#1461 encode & decode id params
  packages/core/src/components/buttons/clone/index.tsx
  packages/core/src/components/buttons/delete/index.tsx
  packages/core/src/components/buttons/edit/index.tsx
  packages/core/src/components/buttons/refresh/index.tsx
  packages/core/src/components/buttons/show/index.tsx
  packages/core/src/components/crud/edit/index.tsx
  packages/core/src/components/crud/show/index.tsx
  packages/core/src/hooks/form/useCloneForm/useCloneForm.ts
  packages/core/src/hooks/form/useEditForm/useEditForm.ts
  packages/core/src/hooks/navigation/index.spec.tsx
  packages/core/src/hooks/navigation/index.ts
  packages/core/src/hooks/show/useShow.ts
  packages/nextjs-router/src/nextRouteComponent.tsx
  packages/react-location/src/resourceComponent.tsx
  packages/react-router/src/routeProvider.tsx
Labels: review-required, auto-merge

#1476 useTable Doc in Core
  documentation/docs/core/hooks/useTable.md
  documentation/sidebars.js
  packages/core/src/hooks/useTable/index.ts
Labels: pr-ready, review-required, auto-merge

#1477 refine-react-table Package Documentation
  documentation/docs/core/hooks/useTable.md
  documentation/docs/examples/react-table/react-table.md
  documentation/docs/packages/react-table.md
  documentation/sidebars.js
  documentation/static/img/packages/react-table/basic.png
  documentation/static/img/packages/react-table/filtering.gif
  documentation/static/img/packages/react-table/pagination.gif
  documentation/static/img/packages/react-table/sorting.gif
  examples/reactTable/.gitignore
  examples/reactTable/package.json
  examples/reactTable/public/favicon.ico
  examples/reactTable/public/index.html
  examples/reactTable/public/manifest.json
  examples/reactTable/src/App.css
  examples/reactTable/src/App.tsx
  examples/reactTable/src/index.tsx
  examples/reactTable/src/interfaces/index.d.ts
  examples/reactTable/src/pages/posts/index.tsx
  examples/reactTable/src/pages/posts/list.tsx
  examples/reactTable/src/react-app-env.d.ts
  examples/reactTable/src/react-table-config.d.ts
  examples/reactTable/tsconfig.json
Labels: review-required, auto-merge

#1487 refine overview description update
  README.md
  documentation/docs/getting-started/overview.md
  documentation/src/components/hero/index.js
  documentation/src/pages/index.js
  packages/ably/README.md
  packages/ably/package.json
  packages/airtable/README.md
  packages/airtable/package.json
  packages/altogic/README.md
  packages/altogic/package.json
  packages/antd/README.md
  packages/antd/package.json
  packages/appwrite/README.md
  packages/codemod/README.md
  packages/codemod/package.json
  packages/core/README.md
  packages/core/package.json
  packages/demo-sidebar/package.json
  packages/graphql/README.md
  packages/graphql/package.json
  packages/hasura/README.md
  packages/hasura/package.json
  packages/nestjsx-crud/README.md
  packages/nestjsx-crud/package.json
  packages/nextjs-router/README.md
  packages/nextjs-router/package.json
  packages/react-hook-form/README.md
  packages/react-location/README.md
  packages/react-location/package.json
  packages/react-router/README.md
  packages/react-router/package.json
  packages/react-table/README.md
  packages/simple-rest/README.md
  packages/simple-rest/package.json
  packages/strapi-graphql/README.md
  packages/strapi-graphql/package.json
  packages/strapi-v4/README.md
  packages/strapi-v4/package.json
  packages/strapi/README.md
  packages/strapi/package.json
  packages/supabase/README.md
  packages/supabase/package.json
Labels: pr-ready, review-required, auto-merge

#1492 refine learn basics docs created
  documentation/docs/getting-started/learn-basics.md
  documentation/sidebars.js
Labels: pr-ready, review-required, auto-merge

#1494 add useModal core doc
  documentation/docs/core/hooks/useModal.md
  documentation/docs/examples/core/useModal.md
  documentation/sidebars.js
  examples/core/useModal/.gitignore
  examples/core/useModal/package.json
  examples/core/useModal/public/favicon.ico
  examples/core/useModal/public/index.html
  examples/core/useModal/public/manifest.json
  examples/core/useModal/src/App.tsx
  examples/core/useModal/src/index.tsx
  examples/core/useModal/src/interfaces/index.d.ts
  examples/core/useModal/src/pages/posts/index.tsx
  examples/core/useModal/src/pages/posts/list.tsx
  examples/core/useModal/src/react-app-env.d.ts
  examples/core/useModal/tsconfig.json
Labels: review-required, auto-merge

#1491 Add useForm in Core Documentation
  documentation/docs/core/hooks/useForm.md
  documentation/sidebars.js
  packages/antd/src/hooks/form/useForm.ts
  packages/core/src/hooks/form/useForm.ts
Labels: pr-ready, review-required, auto-merge

#1496 duplicate tutorial content issue fixed
  documentation/docs/core/tutorial.md
  documentation/docs/tutorial.md
  documentation/docs/ui-frameworks/antd/tutorial.md
Labels: review-required, auto-merge

#1497 add core useImport doc
  documentation/docs/core/hooks/useImport.md
  documentation/docs/examples/core/useImport.md
  documentation/docs/tutorial.md
  documentation/sidebars.js
  documentation/static/img/core/useImport/useImport.gif
  examples/core/useImport/.gitignore
  examples/core/useImport/package.json
  examples/core/useImport/public/favicon.ico
  examples/core/useImport/public/index.html
  examples/core/useImport/public/manifest.json
  examples/core/useImport/src/App.tsx
  examples/core/useImport/src/index.tsx
  examples/core/useImport/src/interfaces/index.d.ts
  examples/core/useImport/src/pages/posts/index.tsx
  examples/core/useImport/src/pages/posts/list.tsx
  examples/core/useImport/src/react-app-env.d.ts
  examples/core/useImport/tsconfig.json
  packages/antd/src/hooks/form/useDrawerForm/useDrawerForm.ts
  packages/antd/src/hooks/form/useModalForm/useModalForm.ts
  packages/antd/src/hooks/form/useStepsForm/useStepsForm.ts
  packages/antd/src/hooks/table/useEditableTable/useEditableTable.ts
  packages/core/src/hooks/import/index.tsx
  packages/react-hook-form/src/useForm/index.ts
Labels: review-required, auto-merge
