Repository refinedev/refine, pull requests merged in 2022-03, with the labels that each got.

#1602 refine-invoice-blog-p2
  documentation/blog/2022-03-01-refine-invoice-genarator-p2.md
  documentation/static/icons/backends/nhost.png
  documentation/static/icons/backends/nhost@2x.png
  documentation/static/img/blog/2022-03-01-refine-invoice-generator-p2/create_invoice.gif
  documentation/static/img/blog/2022-03-01-refine-invoice-generator-p2/invoice.png
  documentation/static/img/blog/2022-03-01-refine-invoice-generator-p2/invoice_list.png
  documentation/static/img/blog/2022-03-01-refine-invoice-generator-p2/invoice_pdf.gif
  documentation/static/img/blog/2022-03-01-refine-invoice-generator-p2/mission_create.gif
  documentation/static/img/blog/2022-03-01-refine-invoice-generator-p2/mission_page.png
  documentation/static/img/blog/2022-03-01-refine-invoice-generator-p2/missions.png
  examples/blog/invoiceGenerator/package.json
  examples/blog/invoiceGenerator/public/favicon.ico
  examples/blog/invoiceGenerator/public/index.html
  examples/blog/invoiceGenerator/public/refine_logo.png
  examples/blog/invoiceGenerator/src/App.tsx
  examples/blog/invoiceGenerator/src/authProvider.ts
  examples/blog/invoiceGenerator/src/components/client/create.tsx
  examples/blog/invoiceGenerator/src/components/client/edit.tsx
  examples/blog/invoiceGenerator/src/components/client/index.ts
  examples/blog/invoiceGenerator/src/components/client/item.tsx
  examples/blog/invoiceGenerator/src/components/company/create.tsx
  examples/blog/invoiceGenerator/src/components/company/edit.tsx
  examples/blog/invoiceGenerator/src/components/company/index.ts
  examples/blog/invoiceGenerator/src/components/company/item.tsx
  examples/blog/invoiceGenerator/src/components/contacts/create.tsx
  examples/blog/invoiceGenerator/src/components/contacts/index.ts
  examples/blog/invoiceGenerator/src/components/mission/create.tsx
  examples/blog/invoiceGenerator/src/components/mission/edit.tsx
  examples/blog/invoiceGenerator/src/components/mission/index.ts
  examples/blog/invoiceGenerator/src/components/pdf/index.ts
  examples/blog/invoiceGenerator/src/components/pdf/pdf.css
  examples/blog/invoiceGenerator/src/components/pdf/pdfLayout.tsx
  examples/blog/invoiceGenerator/src/constants.ts
  examples/blog/invoiceGenerator/src/index.tsx
  examples/blog/invoiceGenerator/src/interfaces/index.d.ts
  examples/blog/invoiceGenerator/src/meta.json
  examples/blog/invoiceGenerator/src/pages/client/index.ts
  examples/blog/invoiceGenerator/src/pages/client/list.tsx
  examples/blog/invoiceGenerator/src/pages/company/index.ts
  examples/blog/invoiceGenerator/src/pages/company/list.tsx
  examples/blog/invoiceGenerator/src/pages/contacts/edit.tsx
  examples/blog/invoiceGenerator/src/pages/contacts/index.ts
  examples/blog/invoiceGenerator/src/pages/contacts/list.tsx
  examples/blog/invoiceGenerator/src/pages/invoice/create.tsx
  examples/blog/invoiceGenerator/src/pages/invoice/edit.tsx
  examples/blog/invoiceGenerator/src/pages/invoice/index.ts
  examples/blog/invoiceGenerator/src/pages/invoice/list.tsx
  examples/blog/invoiceGenerator/src/pages/mission/index.ts
  examples/blog/invoiceGenerator/src/pages/mission/list.tsx
  examples/blog/invoiceGenerator/src/react-app-env.d.ts
  examples/blog/invoiceGenerator/src/reportWebVitals.ts
  examples/blog/invoiceGenerator/src/setupTests.ts
  examples/blog/invoiceGenerator/tsconfig.json
Labels: auto-merge

#1605 refine-invoice-blog-p1 to p2 link added
  documentation/blog/2022-02-22-refine-invoice-genarator.md
Labels: review-required, auto-merge

#1610 remove unused dashboard property of LayoutWrapper component
  documentation/docs/core/components/layout-wrapper.md
  examples/dataProvider/nhost/package.json
  examples/dataProvider/nhost/src/App.tsx
  packages/antd/src/components/layout/index.tsx
  packages/core/src/components/layoutWrapper/index.tsx
Labels: review-required, auto-merge, build examples

#1606 descriptions for refine examples
  documentation/docs/examples/access-control/casbin.md
  documentation/docs/examples/access-control/cerbos.md
  documentation/docs/examples/auth-provider/auth0.md
  documentation/docs/examples/auth-provider/google-auth.md
  documentation/docs/examples/auth-provider/otpLogin.md
  documentation/docs/examples/authorization.md
  documentation/docs/examples/custom-pages.md
  documentation/docs/examples/data-provider/airtable.md
  documentation/docs/examples/data-provider/altogic.md
  documentation/docs/examples/data-provider/appwrite.md
  documentation/docs/examples/data-provider/hasura.md
  documentation/docs/examples/data-provider/multiple.md
  documentation/docs/examples/data-provider/nestjsxCrud.md
  documentation/docs/examples/data-provider/nhost.md
  documentation/docs/examples/data-provider/strapi-graphql.md
  documentation/docs/examples/data-provider/strapi-v4.md
  documentation/docs/examples/data-provider/strapi.md
  documentation/docs/examples/data-provider/supabase.md
  documentation/docs/examples/live-provider/ably.md
  documentation/docs/examples/tutorial.md
Labels: review-required, auto-merge

#1598 Add "or" operator to CrudFilter
  documentation/docs/guides-and-concepts/data-provider/handling-filters.md
  documentation/sidebars.js
  examples/dataProvider/strapi-graphql/src/interfaces/index.d.ts
  examples/dataProvider/strapi-graphql/src/pages/posts/edit.tsx
  examples/dataProvider/strapi-graphql/src/pages/posts/list.tsx
  examples/dataProvider/strapi-graphql/src/pages/posts/show.tsx
  packages/airtable/src/index.ts
  packages/altogic/src/index.ts
  packages/antd/src/definitions/table/index.ts
  packages/appwrite/src/index.ts
  packages/core/src/contexts/data/IDataContext.ts
  packages/core/src/definitions/table/__snapshots__/index.spec.ts.snap
  packages/core/src/definitions/table/index.spec.ts
  packages/core/src/definitions/table/index.ts
  packages/core/src/index.tsx
  packages/graphql/src/index.ts
  packages/graphql/test/getList/index.mock.ts
  packages/graphql/test/getList/index.spec.ts
  packages/graphql/test/gqlClient.ts
  packages/hasura/src/index.ts
  packages/nestjsx-crud/src/index.ts
  packages/nhost/src/index.ts
  packages/react-table/src/useTable/index.ts
  packages/simple-rest/src/index.ts
  packages/strapi-graphql/src/index.ts
  packages/strapi-v4/src/dataProvider.ts
  packages/strapi/src/dataProvider.ts
  packages/supabase/src/index.ts
  packages/supabase/test/getList/index.spec.ts
Labels: auto-merge, build examples

#1613 descriptions to refine examples
  documentation/docs/examples/core/useImport.md
  documentation/docs/examples/core/useModal.md
  documentation/docs/examples/data-provider/airtable.md
  documentation/docs/examples/data-provider/altogic.md
  documentation/docs/examples/data-provider/appwrite.md
  documentation/docs/examples/data-provider/hasura.md
  documentation/docs/examples/data-provider/nestjsxCrud.md
  documentation/docs/examples/data-provider/nhost.md
  documentation/docs/examples/data-provider/strapi-graphql.md
  documentation/docs/examples/data-provider/strapi-v4.md
  documentation/docs/examples/data-provider/strapi.md
  documentation/docs/examples/data-provider/supabase.md
  documentation/docs/examples/form/custom-form-validation.md
  documentation/docs/examples/form/useDrawerForm.md
  documentation/docs/examples/form/useForm.md
  documentation/docs/examples/form/useModalForm.md
  documentation/docs/examples/form/useStepsForm.md
  documentation/docs/examples/i18n/i18n-nextjs.md
  documentation/docs/examples/i18n/i18n-react.md
  documentation/docs/examples/notification-provider/react-toastify.md
  documentation/docs/examples/router-provider/react-location.md
Labels: review-required, auto-merge

#1583 Refactor react query keys
  packages/core/src/components/containers/refine/index.tsx
  packages/core/src/definitions/helpers/index.ts
  packages/core/src/definitions/helpers/queryKeys/index.ts
  packages/core/src/hooks/data/useCreate.ts
  packages/core/src/hooks/data/useCreateMany.ts
  packages/core/src/hooks/data/useCustom.ts
  packages/core/src/hooks/data/useDelete.ts
  packages/core/src/hooks/data/useDeleteMany.ts
  packages/core/src/hooks/data/useList.ts
  packages/core/src/hooks/data/useMany.ts
  packages/core/src/hooks/data/useOne.ts
  packages/core/src/hooks/data/useUpdate.ts
  packages/core/src/hooks/data/useUpdateMany.ts
  packages/core/src/interfaces/index.ts
  packages/core/src/interfaces/mutationMode.ts
  packages/core/src/interfaces/queryKey.ts
Labels: pr-onhold, review-required, auto-merge, build examples

#1619 fix nextjs-router package
  packages/core/package.json
  packages/core/tsup.config.ts
  packages/nextjs-router/package.json
  packages/nextjs-router/tsup.config.ts
Labels: review-required, auto-merge

#1623 Fix finefood sync location bug on products page
  examples/fineFoods/admin/src/components/product/productCategoryFilter.tsx
  examples/fineFoods/admin/src/pages/products/list.tsx
Labels: pr-ready, auto-merge

#1629 DeleteButton props updated in the related docs
  documentation/docs/ui-frameworks/antd/components/buttons/delete.md
Labels: review-required, auto-merge

#1628 add popconfirm text props to delete button
  documentation/docs/ui-frameworks/antd/components/buttons/delete.md
  packages/antd/src/components/buttons/delete/index.tsx
Labels: review-required, auto-merge

#1625 Use radio group docs
  documentation/docs/ui-frameworks/antd/hooks/field/useCheckboxGroup.md
  documentation/docs/ui-frameworks/antd/hooks/field/useRadioGroup.md
Labels: review-required, auto-merge

#1624 Use radio group antd refactor
  documentation/docs/ui-frameworks/antd/hooks/field/useCheckboxGroup.md
  documentation/docs/ui-frameworks/antd/hooks/field/useRadioGroup.md
  packages/antd/src/hooks/fields/useCheckboxGroup/index.ts
  packages/antd/src/hooks/fields/useRadioGroup/index.ts
  packages/core/src/hooks/useSelect/index.ts
Labels: review-required, auto-merge

#1633 fix onClick event issue for antd buttons
  packages/antd/src/components/buttons/clone/index.tsx
  packages/antd/src/components/buttons/create/index.tsx
  packages/antd/src/components/buttons/edit/index.tsx
  packages/antd/src/components/buttons/list/index.tsx
  packages/antd/src/components/buttons/refresh/index.tsx
  packages/antd/src/components/buttons/show/index.tsx
Labels: review-required, auto-merge

#1636 Description for examples
  documentation/docs/examples/customization/customFooter.md
  documentation/docs/examples/customization/customLogin.md
  documentation/docs/examples/customization/customSider.md
  documentation/docs/examples/customization/offLayoutArea.md
  documentation/docs/examples/customization/rtl.md
  documentation/docs/examples/customization/topMenuLayout.md
  documentation/docs/examples/e2e-testing.md
  documentation/docs/examples/import-export.md
  documentation/docs/examples/javascript.md
  documentation/docs/examples/multi-tenancy/appwrite.md
  documentation/docs/examples/multi-tenancy/strapi-v4.md
  documentation/docs/examples/theme.md
  documentation/docs/examples/web3/signin-ethereum.md
Labels: pr-ready, review-required, auto-merge

#1639 Fix react-router-v6 not matched route warning
  packages/react-router-v6/src/routeProvider.tsx
Labels: review-required, auto-merge

#1643 Fix react-router-v6 resource name match
  packages/react-router-v6/src/routeProvider.tsx
Labels: review-required, auto-merge

#1644 fix wrong set id after mutation on useForm
  packages/antd/src/hooks/form/useDrawerForm/useDrawerForm.ts
  packages/core/src/hooks/form/useForm.ts
Labels: review-required

#1637 Feature: save and continue editing logic for forms
  documentation/docs/core/hooks/useForm.md
  documentation/docs/ui-frameworks/antd/hooks/form/useForm.md
  documentation/docs/ui-frameworks/antd/hooks/form/useModalForm.md
  documentation/docs/ui-frameworks/antd/hooks/form/useStepsForm.md
  packages/antd/src/hooks/form/useForm.ts
  packages/core/src/hooks/form/useForm.ts
  packages/core/src/hooks/redirection/index.spec.tsx
  packages/core/src/hooks/redirection/index.ts
  packages/react-hook-form/src/useForm/index.ts
Labels: auto-merge

#1647 handle custom routes on CRUD componenets and buttons
  documentation/docs/ui-frameworks/antd/components/buttons/clone.md
  documentation/docs/ui-frameworks/antd/components/buttons/create.md
  documentation/docs/ui-frameworks/antd/components/buttons/delete.md
  documentation/docs/ui-frameworks/antd/components/buttons/edit.md
  documentation/docs/ui-frameworks/antd/components/buttons/list.md
  documentation/docs/ui-frameworks/antd/components/buttons/refresh.md
  documentation/docs/ui-frameworks/antd/components/buttons/show.md
  packages/antd/src/components/buttons/clone/index.spec.tsx
  packages/antd/src/components/buttons/clone/index.tsx
  packages/antd/src/components/buttons/create/index.spec.tsx
  packages/antd/src/components/buttons/create/index.tsx
  packages/antd/src/components/buttons/delete/index.spec.tsx
  packages/antd/src/components/buttons/delete/index.tsx
  packages/antd/src/components/buttons/edit/index.spec.tsx
  packages/antd/src/components/buttons/edit/index.tsx
  packages/antd/src/components/buttons/list/index.spec.tsx
  packages/antd/src/components/buttons/list/index.tsx
  packages/antd/src/components/buttons/refresh/index.tsx
  packages/antd/src/components/buttons/show/index.spec.tsx
  packages/antd/src/components/buttons/show/index.tsx
  packages/antd/src/components/crud/edit/index.tsx
  packages/antd/src/components/crud/list/index.tsx
  packages/antd/src/components/crud/show/index.tsx
  packages/core/src/hooks/resource/useResourceWithRoute/index.ts
Labels: review-required, auto-merge

#1650 internal-tool frameworks blog
  documentation/blog/2022-03-16-internal-tool-frameworks.md
  documentation/static/img/blog/2022-03-16-internal-tool-frameworks/react_admin.png
  documentation/static/img/blog/2022-03-16-internal-tool-frameworks/redwood.png
  documentation/static/img/blog/2022-03-16-internal-tool-frameworks/refine-admin-panel.png
  documentation/static/img/blog/2022-03-16-internal-tool-frameworks/refine_client.png
  documentation/static/img/blog/2022-03-16-internal-tool-frameworks/superplate.gif
Labels: review-required, auto-merge

#1652 Fix <ShowButton /> doesn't work with the Tooltip (Ant Design) component
  packages/antd/src/components/buttons/show/index.tsx
Labels: pr-ready, auto-merge

#1658 Fix live provider invalidate issue
  packages/ably/src/index.ts
  packages/core/src/hooks/index.ts
  packages/core/src/hooks/live/useResourceSubscription/index.ts
  packages/core/src/hooks/useListResourceQueries.ts
  packages/supabase/src/index.ts
Labels: auto-merge

#1660 refine-win95-example
  documentation/blog/2022-03-22-refine-with-react95.md
  documentation/static/img/blog/2022-03-22-refine-with-react95/advanced_table.gif
  documentation/static/img/blog/2022-03-22-refine-with-react95/create_edit.gif
  documentation/static/img/blog/2022-03-22-refine-with-react95/menu.gif
  documentation/static/img/blog/2022-03-22-refine-with-react95/overview.gif
  documentation/static/img/blog/2022-03-22-refine-with-react95/refine_login.png
  documentation/static/img/blog/2022-03-22-refine-with-react95/refine_setup.gif
  documentation/static/img/blog/2022-03-22-refine-with-react95/table.png
  documentation/static/img/blog/2022-03-22-refine-with-react95/top_menu.gif
  examples/blog/win95/package.json
  examples/blog/win95/public/favicon.ico
  examples/blog/win95/public/index.html
  examples/blog/win95/public/refine.png
  examples/blog/win95/src/App.tsx
  examples/blog/win95/src/app.css
  examples/blog/win95/src/authProvider.ts
  examples/blog/win95/src/components/bar/index.tsx
  examples/blog/win95/src/components/footer/index.tsx
  examples/blog/win95/src/index.tsx
  examples/blog/win95/src/interfaces/index.d.ts
  examples/blog/win95/src/meta.json
  examples/blog/win95/src/pages/category/create.tsx
  examples/blog/win95/src/pages/category/edit.tsx
  examples/blog/win95/src/pages/category/index.ts
  examples/blog/win95/src/pages/category/list.tsx
  examples/blog/win95/src/pages/login/index.tsx
  examples/blog/win95/src/pages/posts/create.tsx
  examples/blog/win95/src/pages/posts/edit.tsx
  examples/blog/win95/src/pages/posts/index.ts
  examples/blog/win95/src/pages/posts/list.tsx
  examples/blog/win95/src/react-app-env.d.ts
  examples/blog/win95/src/reportWebVitals.ts
  examples/blog/win95/src/setupTests.ts
  examples/blog/win95/src/utility/index.ts
  examples/blog/win95/src/utility/supabaseClient.ts
  examples/blog/win95/tsconfig.json
Labels: review-required, auto-merge

#1663 typo fixed and added missing title
  documentation/blog/2022-03-22-refine-with-react95.md
Labels: review-required, auto-merge

#1667 react-hook-form multipart file upload blog
  documentation/blog/2022-03-29-react-hook-form-upload.md
  documentation/docs/packages/react-hook-form.md
  documentation/static/img/blog/2022-03-29-react-hook-form-upload/image_upload.gif
  documentation/static/img/blog/2022-03-29-react-hook-form-upload/overview.gif
  documentation/static/img/blog/2022-03-29-react-hook-form-upload/server_start.gif
  documentation/static/img/packages/react-hook-form/upload.gif
  examples/reactHookForm/package.json
  examples/reactHookForm/src/pages/posts/create.tsx
  examples/reactHookForm/src/pages/posts/edit.tsx
  examples/reactHookForm/src/pages/posts/list.tsx
Labels: review-required, auto-merge

#1671 added tip to customize login error notification to authProvider docum…
  documentation/docs/core/providers/auth-provider.md
Labels: review-required, auto-merge

#1672 antd useTable sorting operation column key and dataIndex prop explana…
  documentation/docs/ui-frameworks/antd/hooks/table/useTable.md
Labels: review-required, auto-merge
