Repository refinedev/refine, pull requests merged in 2022-02, with the labels that each got.

#1498 add useSelect hook core doc
  documentation/docs/core/hooks/useSelect.md
  documentation/docs/examples/core/useSelect.md
  documentation/sidebars.js
  documentation/static/img/core/useSelect/useSelect.png
  examples/core/useSelect/.gitignore
  examples/core/useSelect/package.json
  examples/core/useSelect/public/favicon.ico
  examples/core/useSelect/public/index.html
  examples/core/useSelect/public/manifest.json
  examples/core/useSelect/src/App.tsx
  examples/core/useSelect/src/index.tsx
  examples/core/useSelect/src/interfaces/index.d.ts
  examples/core/useSelect/src/pages/posts/index.tsx
  examples/core/useSelect/src/pages/posts/list.tsx
  examples/core/useSelect/src/react-app-env.d.ts
  examples/core/useSelect/tsconfig.json
Labels: review-required, auto-merge

#1501 add useNotification hook doc
  documentation/docs/core/hooks/useNotification.md
  documentation/docs/core/providers/notification-provider.md
  documentation/sidebars.js
Labels: review-required, auto-merge

#1502 tutorial card created
  documentation/docs/getting-started/overview.md
  documentation/docs/tutorial.md
  documentation/src/components/tutorial-card/index.js
  documentation/src/components/tutorial-card/styles.module.css
  documentation/static/icons/nextjs.svg
Labels: review-required, auto-merge

#1503 Refine Reack Hook Form Doc and Example
  documentation/docs/examples/react-hook-form/react-hook-form.md
  documentation/docs/packages/react-hook-form.md
  documentation/docs/packages/react-table.md
  documentation/sidebars.js
  documentation/static/img/packages/react-hook-form/create-form.gif
  documentation/static/img/packages/react-hook-form/edit-form.gif
  documentation/static/img/packages/react-hook-form/list-page.png
  examples/fineFoods/client/pages/[id]/[category]/index.tsx
  examples/reactHookForm/package.json
  examples/reactHookForm/public/favicon.ico
  examples/reactHookForm/public/index.html
  examples/reactHookForm/public/manifest.json
  examples/reactHookForm/src/App.tsx
  examples/reactHookForm/src/index.tsx
  examples/reactHookForm/src/interfaces/index.d.ts
  examples/reactHookForm/src/pages/posts/create.tsx
  examples/reactHookForm/src/pages/posts/edit.tsx
  examples/reactHookForm/src/pages/posts/index.tsx
  examples/reactHookForm/src/pages/posts/list.tsx
  examples/reactHookForm/src/react-app-env.d.ts
  examples/reactHookForm/tsconfig.json
  examples/tailwind/src/pages/posts/create.tsx
  examples/tailwind/src/pages/posts/edit.tsx
  packages/core/src/hooks/form/useForm.ts
  packages/core/src/hooks/useSelect/index.ts
  packages/react-hook-form/src/useForm/index.ts
  packages/react-table/src/useTable/index.spec.ts
  packages/react-table/src/useTable/index.ts
Labels: review-required, auto-merge

#1509 Update Notification Provider Doc
  documentation/docs/core/providers/notification-provider.md
  documentation/docs/examples/react-toastify/react-toastify.md
  documentation/sidebars.js
  examples/baseHeadless/package.json
  examples/baseHeadless/public/favicon.ico
  examples/baseHeadless/public/index.html
  examples/baseHeadless/public/manifest.json
  examples/baseHeadless/src/App.css
  examples/baseHeadless/src/App.tsx
  examples/baseHeadless/src/index.tsx
  examples/baseHeadless/src/interfaces/index.d.ts
  examples/baseHeadless/src/pages/posts/create.tsx
  examples/baseHeadless/src/pages/posts/edit.tsx
  examples/baseHeadless/src/pages/posts/index.tsx
  examples/baseHeadless/src/pages/posts/list.tsx
  examples/baseHeadless/src/react-app-env.d.ts
  examples/baseHeadless/src/react-table-config.d.ts
  examples/baseHeadless/tsconfig.json
  examples/reactToastify/package.json
  examples/reactToastify/public/favicon.ico
  examples/reactToastify/public/index.html
  examples/reactToastify/public/manifest.json
  examples/reactToastify/src/App.css
  examples/reactToastify/src/App.tsx
  examples/reactToastify/src/components/undoableNotification.tsx
  examples/reactToastify/src/index.tsx
  examples/reactToastify/src/interfaces/index.d.ts
  examples/reactToastify/src/pages/posts/create.tsx
  examples/reactToastify/src/pages/posts/edit.tsx
  examples/reactToastify/src/pages/posts/index.tsx
  examples/reactToastify/src/pages/posts/list.tsx
  examples/reactToastify/src/providers/notificationProvider.tsx
  examples/reactToastify/src/react-app-env.d.ts
  examples/reactToastify/src/react-table-config.d.ts
  examples/reactToastify/tsconfig.json
Labels: review-required, auto-merge

#1508 [Bug] Decode id fix on buttons and cloneForm
  packages/core/src/components/buttons/clone/index.tsx
  packages/core/src/components/buttons/delete/index.tsx
  packages/core/src/components/buttons/edit/index.tsx
  packages/core/src/components/buttons/refresh/index.tsx
  packages/core/src/components/buttons/show/index.tsx
  packages/core/src/hooks/form/useCloneForm/useCloneForm.ts
Labels: review-required, auto-merge

#1521 added migration guide for v3.x.x
  documentation/docs/migration-guide.md
  packages/codemod/src/transformations/refine2-to-refine3.ts
Labels: review-required, auto-merge

#1511 Headless Tutorial Example and Doc
  documentation/docs/core/tutorial.md
  documentation/package-lock.json
  documentation/static/img/core/tutorial/create.gif
  documentation/static/img/core/tutorial/edit.gif
  documentation/static/img/core/tutorial/ready-page.png
  documentation/static/img/core/tutorial/resource-1.png
  documentation/static/img/core/tutorial/resource-2.png
  documentation/static/img/core/tutorial/show.gif
  examples/fineFoods/client/pages/[id]/[category]/index.tsx
  examples/fineFoods/client/pages/index.tsx
  examples/fineFoods/client/pages/order/[id]/index.tsx
  examples/fineFoods/client/src/components/categoryCard.tsx
  examples/fineFoods/client/src/components/footer.tsx
  examples/fineFoods/client/src/components/header.tsx
  examples/fineFoods/client/src/components/layout.tsx
  examples/fineFoods/client/src/components/numberInput.tsx
  examples/fineFoods/client/src/components/orderModalProductItem.tsx
  examples/fineFoods/client/src/components/ordersModal.tsx
  examples/fineFoods/client/src/components/productCard.tsx
  examples/fineFoods/client/src/components/productListItem.tsx
  examples/fineFoods/client/src/components/promotional.tsx
  examples/tutorial/antd/.gitignore
  examples/tutorial/antd/package.json
  examples/tutorial/antd/public/favicon.ico
  examples/tutorial/antd/public/index.html
  examples/tutorial/antd/public/manifest.json
  examples/tutorial/antd/src/App.tsx
  examples/tutorial/antd/src/index.tsx
  examples/tutorial/antd/src/interfaces/index.d.ts
  examples/tutorial/antd/src/pages/index.ts
  examples/tutorial/antd/src/pages/posts/create.tsx
  examples/tutorial/antd/src/pages/posts/edit.tsx
  examples/tutorial/antd/src/pages/posts/index.tsx
  examples/tutorial/antd/src/pages/posts/list.tsx
  examples/tutorial/antd/src/pages/posts/show.tsx
  examples/tutorial/antd/src/react-app-env.d.ts
  examples/tutorial/antd/tsconfig.json
  examples/tutorial/headless/package.json
  examples/tutorial/headless/postcss.config.js
  examples/tutorial/headless/public/favicon.ico
  examples/tutorial/headless/public/index.html
  examples/tutorial/headless/public/manifest.json
  examples/tutorial/headless/src/App.tsx
  examples/tutorial/headless/src/components/index.ts
  examples/tutorial/headless/src/components/layout.tsx
  examples/tutorial/headless/src/icons.tsx
  examples/tutorial/headless/src/index.css
  examples/tutorial/headless/src/index.tsx
  examples/tutorial/headless/src/interfaces/index.d.ts
  examples/tutorial/headless/src/pages/posts/create.tsx
  examples/tutorial/headless/src/pages/posts/edit.tsx
  examples/tutorial/headless/src/pages/posts/index.tsx
  examples/tutorial/headless/src/pages/posts/list.tsx
  examples/tutorial/headless/src/pages/posts/show.tsx
  examples/tutorial/headless/src/react-app-env.d.ts
  examples/tutorial/headless/src/react-table-config.d.ts
  examples/tutorial/headless/tailwind.config.js
  examples/tutorial/headless/tsconfig.json
  packages/react-table/src/useTable/index.ts
Labels: review-required, auto-merge

#1524 Improve Core Tutorial
  documentation/docs/core/tutorial.md
  documentation/static/img/core/tutorial/edit.gif
  documentation/static/img/core/tutorial/pagination.png
  documentation/static/img/core/tutorial/relation.png
  documentation/static/img/core/tutorial/show.gif
  documentation/static/img/core/tutorial/sort-and-filter.gif
  examples/tutorial/headless/src/pages/posts/list.tsx
Labels: review-required, auto-merge

#1528 Typo fix - multi-tenancy-strapi guide
  documentation/docs/guides-and-concepts/multi-tenancy/strapi.md
  documentation/versioned_docs/version-2.xx.xx/guides-and-concepts/multi-tenancy/strapi-v4.md
Labels: review-required, auto-merge

#1530 Custom redirect on login
  documentation/docs/core/hooks/auth/useLogin.md
  documentation/docs/core/hooks/auth/useLogout.md
  packages/core/src/contexts/auth/IAuthContext.ts
  packages/core/src/contexts/auth/index.tsx
  packages/core/src/hooks/auth/useCheckError/index.spec.ts
  packages/core/src/hooks/auth/useCheckError/index.ts
  packages/core/src/hooks/auth/useLogin/index.spec.ts
  packages/core/src/hooks/auth/useLogin/index.ts
  packages/core/src/hooks/auth/useLogout/index.spec.ts
  packages/core/src/hooks/auth/useLogout/index.ts
Labels: pr-ready, review-required, auto-merge

#1532 Strapi v4 Normalization Data
  examples/dataProvider/strapi-v4/src/pages/posts/list.tsx
  packages/strapi-v4/src/dataProvider.ts
Labels: review-required, auto-merge

#1543 [Fix] Router crashes refine-nextjs app
  packages/nextjs-router/package.json
Labels: review-required, auto-merge

#1541 Update Strapi Examples by Strapi v4 Normalization
  documentation/docs/guides-and-concepts/data-provider/strapi-v4.md
  documentation/docs/guides-and-concepts/multi-tenancy/strapi.md
  examples/dataProvider/strapi-v4/src/interfaces/index.d.ts
  examples/dataProvider/strapi-v4/src/pages/posts/edit.tsx
  examples/multi-tenancy/strapi/package.json
  examples/multi-tenancy/strapi/src/authProvider.ts
  examples/multi-tenancy/strapi/src/components/product/create.tsx
  examples/multi-tenancy/strapi/src/components/product/edit.tsx
  examples/multi-tenancy/strapi/src/components/product/item.tsx
  examples/multi-tenancy/strapi/src/interfaces/index.d.ts
  examples/multi-tenancy/strapi/src/pages/order/create.tsx
  examples/multi-tenancy/strapi/src/pages/order/edit.tsx
  examples/multi-tenancy/strapi/src/pages/order/list.tsx
  packages/strapi-v4/src/dataProvider.ts
  packages/strapi-v4/src/helpers/normalize.ts
Labels: review-required, auto-merge

#1549 refine-ecommerce-blog
  documentation/blog/2022-02-14-refine-ecommerce-blog.md
  documentation/static/img/blog/2022-02-14-refine-ecommerce-blog/basket.gif
  documentation/static/img/blog/2022-02-14-refine-ecommerce-blog/layout.png
  documentation/static/img/blog/2022-02-14-refine-ecommerce-blog/page_size.gif
  documentation/static/img/blog/2022-02-14-refine-ecommerce-blog/pagination.gif
  documentation/static/img/blog/2022-02-14-refine-ecommerce-blog/products.png
  documentation/static/img/blog/2022-02-14-refine-ecommerce-blog/sample_product.png
  examples/blog/ecommerce/next-env.d.ts
  examples/blog/ecommerce/next.config.js
  examples/blog/ecommerce/package.json
  examples/blog/ecommerce/pages/_app.tsx
  examples/blog/ecommerce/pages/index.tsx
  examples/blog/ecommerce/public/error.png
  examples/blog/ecommerce/public/favicon.ico
  examples/blog/ecommerce/public/refine.svg
  examples/blog/ecommerce/public/refine_logo.png
  examples/blog/ecommerce/src/components/filterButton.tsx
  examples/blog/ecommerce/src/components/index.ts
  examples/blog/ecommerce/src/components/layout.tsx
  examples/blog/ecommerce/src/components/productCard.tsx
  examples/blog/ecommerce/src/constants.ts
  examples/blog/ecommerce/src/interfaces/index.ts
  examples/blog/ecommerce/tsconfig.json
Labels: pr-ready, auto-merge

#1551 update ecommerce blog
  documentation/blog/2022-02-14-refine-ecommerce-blog.md
Labels: review-required, auto-merge

#1545 useTableCore implemented to useSimpleList antd
  documentation/docs/ui-frameworks/antd/hooks/list/useSimpleList.md
  documentation/docs/ui-frameworks/antd/hooks/table/useTable.md
  documentation/versioned_docs/version-3.xx.xx/ui-frameworks/antd/hooks/list/useSimpleList.md
  documentation/versioned_docs/version-3.xx.xx/ui-frameworks/antd/hooks/table/useTable.md
  packages/antd/src/hooks/list/useSimpleList/useSimpleList.ts
Labels: auto-merge

#1548 upgrade refine node@16 and npm@8
  documentation/Dockerfile
  documentation/docs/contributing.md
  documentation/versioned_docs/version-3.xx.xx/contributing.md
  examples/fineFoods/admin/Dockerfile
  examples/fineFoods/client/Dockerfile
  package-lock.json
  packages/codemod/package-lock.json
  packages/codemod/package.json
  packages/react-location/src/prompt.tsx
Labels: review-required, auto-merge

#1558 fixed custom resource name error on all buttons
  packages/antd/src/components/buttons/clone/index.spec.tsx
  packages/antd/src/components/buttons/clone/index.tsx
  packages/antd/src/components/buttons/create/index.spec.tsx
  packages/antd/src/components/buttons/edit/index.spec.tsx
  packages/antd/src/components/buttons/edit/index.tsx
  packages/antd/src/components/buttons/show/index.spec.tsx
  packages/antd/src/components/buttons/show/index.tsx
Labels: review-required, auto-merge

#1561 Fix export-to-csv source map error and remove unnecessary dependencies
  package.json
  packages/antd/package.json
  packages/core/package.json
  packages/core/src/hooks/export/index.spec.ts
  packages/core/src/hooks/export/index.ts
Labels: review-required, auto-merge

#1563 New Blog Post -> Build low-code, customizable and authorization ready (accesscontrol) admin panel with NestJS.
  documentation/blog/2022-02-21-build-low-code-customizable-and-authorization-ready-accesscontrol-admin-panel-with-nestjs.md
Labels: review-required, auto-merge

#1562 New Blog Post - Build internal tools using low-code with Refine
  documentation/blog/2022-02-21-build-internal-tools-with-refine.md
Labels: review-required, auto-merge

#1565 New Blog Post -> How to Become A Production Hero as Developer with Refine in 2022
  documentation/blog/2022-02-21-become-production-hero.md
  documentation/blog/authors.yml
Labels: review-required, auto-merge

#1564 New Blog Post -> Top React JS Frameworks Every Developer Should Know
  documentation/blog/2022-02-21-top-react-frameworks.md
  documentation/static/img/blog/2022-02-21-top-react-frameworks/antd.png
  documentation/static/img/blog/2022-02-21-top-react-frameworks/create-react-app.png
  documentation/static/img/blog/2022-02-21-top-react-frameworks/material-ui.png
  documentation/static/img/blog/2022-02-21-top-react-frameworks/react-bootstrap.png
  documentation/static/img/blog/2022-02-21-top-react-frameworks/refine-2.png
  documentation/static/img/blog/2022-02-21-top-react-frameworks/refine.png
Labels: review-required, auto-merge

#1566 react-antd-framework blog
  documentation/blog/2022-02-21-react-antd-admin.md
  documentation/static/img/blog/2022-02-21-react-antd-admin/access-control.gif
  documentation/static/img/blog/2022-02-21-react-antd-admin/access_button.png
  documentation/static/img/blog/2022-02-21-react-antd-admin/i8n-overview.gif
  documentation/static/img/blog/2022-02-21-react-antd-admin/realtime.gif
  documentation/static/img/blog/2022-02-21-react-antd-admin/refine_tutorial.gif
  documentation/static/img/blog/2022-02-21-react-antd-admin/table-i18n.gif
Labels: review-required, auto-merge

#1569 Add Vite example
  documentation/docs/migration-guide.md
  documentation/versioned_docs/version-3.xx.xx/migration-guide.md
  examples/vite/.gitignore
  examples/vite/index.html
  examples/vite/package.json
  examples/vite/src/App.tsx
  examples/vite/src/favicon.ico
  examples/vite/src/main.tsx
  examples/vite/src/pages/posts/create.tsx
  examples/vite/src/pages/posts/edit.tsx
  examples/vite/src/pages/posts/index.tsx
  examples/vite/src/pages/posts/list.tsx
  examples/vite/src/pages/posts/show.tsx
  examples/vite/src/vite-env.d.ts
  examples/vite/tsconfig.json
  examples/vite/tsconfig.node.json
  examples/vite/vite.config.ts
  packages/antd/src/components/crud/edit/index.tsx
  packages/antd/src/components/crud/list/index.tsx
  packages/antd/src/hooks/form/useDrawerForm/useDrawerForm.ts
  packages/antd/src/hooks/form/useForm.ts
  packages/antd/src/hooks/modal/useModal/index.tsx
  packages/antd/src/hooks/table/useEditableTable/useEditableTable.ts
  packages/codemod/src/transformations/refine2-to-refine3.ts
  packages/core/src/components/layoutWrapper/index.spec.tsx
  packages/core/src/components/pages/ready/index.tsx
  packages/core/src/hooks/data/useDataProvider.tsx
  packages/core/src/hooks/data/useList.spec.tsx
  packages/core/src/hooks/data/useMany.spec.tsx
  packages/core/src/hooks/data/useOne.spec.tsx
  packages/core/src/hooks/import/index.spec.tsx
  packages/core/src/hooks/import/index.tsx
  packages/core/src/hooks/live/useLiveMode/index.spec.ts
  packages/core/src/hooks/live/useResourceSubscription/index.spec.ts
  packages/core/src/hooks/notification/useHandleNotification/index.spec.tsx
  packages/core/src/hooks/notification/useHandleNotification/index.ts
  packages/core/src/hooks/redirection/index.ts
  packages/core/src/hooks/useSelect/index.spec.ts
  packages/core/src/interfaces/index.ts
  packages/core/src/interfaces/istate.ts
  packages/core/src/interfaces/reducers/auth/user.d.ts
  packages/core/src/interfaces/reducers/resource/resource.d.ts
Labels: review-required, auto-merge

#1575 add directus package docs
  README.md
  documentation/blog/2022-02-21-become-production-hero.md
  documentation/blog/2022-02-21-top-react-frameworks.md
  documentation/docs/core/providers/data-provider.md
  documentation/docs/core/tutorial.md
  documentation/docs/getting-started/learn-basics.md
  documentation/docs/getting-started/overview.md
  documentation/docs/ui-frameworks/antd/tutorial.md
  documentation/src/components/key-features/index.js
  documentation/versioned_docs/version-2.xx.xx/api-references/providers/data-provider.md
  documentation/versioned_docs/version-2.xx.xx/tutorial.md
  documentation/versioned_docs/version-3.xx.xx/core/providers/data-provider.md
  documentation/versioned_docs/version-3.xx.xx/core/tutorial.md
  documentation/versioned_docs/version-3.xx.xx/getting-started/learn-basics.md
  documentation/versioned_docs/version-3.xx.xx/getting-started/overview.md
  documentation/versioned_docs/version-3.xx.xx/ui-frameworks/antd/tutorial.md
  packages/antd/README.md
  packages/core/README.md
Labels: review-required, auto-merge

#1582 [Fix] React Router v6 resource options
  packages/react-router-v6/src/routeProvider.tsx
Labels: review-required, auto-merge

#1579 refine-invoice-genarator-blog
  documentation/blog/2022-02-22-refine-invoice-genarator.md
  documentation/static/img/blog/2022-02-22-refine-invoice-genarator/client.png
  documentation/static/img/blog/2022-02-22-refine-invoice-genarator/clients_overview.gif
  documentation/static/img/blog/2022-02-22-refine-invoice-genarator/company.png
  documentation/static/img/blog/2022-02-22-refine-invoice-genarator/contact.png
  documentation/static/img/blog/2022-02-22-refine-invoice-genarator/refine_company.png
  documentation/static/img/blog/2022-02-22-refine-invoice-genarator/refine_contacts.png
Labels: review-required, auto-merge

#1587 Router provider document update
  documentation/docs/core/providers/router-provider.md
  documentation/docs/guides-and-concepts/custom-pages.md
Labels: review-required, auto-merge

#1590 Loosen type id document
  documentation/docs/core/hooks/data/useDelete.md
  documentation/docs/core/hooks/data/useDeleteMany.md
  documentation/docs/core/hooks/data/useList.md
  documentation/docs/core/hooks/data/useMany.md
  documentation/docs/core/hooks/data/useOne.md
  documentation/docs/core/hooks/data/useUpdate.md
  documentation/docs/core/hooks/data/useUpdateMany.md
  documentation/docs/core/hooks/show/useShow.md
  documentation/docs/core/hooks/useForm.md
  documentation/docs/core/hooks/useSelect.md
  documentation/docs/core/hooks/useTable.md
  documentation/docs/core/interfaces.md
  documentation/docs/ui-frameworks/antd/components/basic-views/edit.md
  documentation/docs/ui-frameworks/antd/components/basic-views/show.md
  documentation/docs/ui-frameworks/antd/components/buttons/clone.md
  documentation/docs/ui-frameworks/antd/components/buttons/delete.md
  documentation/docs/ui-frameworks/antd/components/buttons/edit.md
  documentation/docs/ui-frameworks/antd/components/buttons/refresh.md
  documentation/docs/ui-frameworks/antd/components/buttons/show.md
Labels: review-required, auto-merge

#1591 Fix refine icons
  documentation/src/components/key-features/index.js
  documentation/src/components/key-features/styles.module.css
  documentation/static/icons/features/fast.png
  documentation/static/icons/features/fast@2x.png
  documentation/static/icons/features/headless.png
  documentation/static/icons/features/headless@2x.png
  documentation/static/icons/features/one-min-setup.png
  documentation/static/icons/features/one-min-setup@2x.png
  documentation/static/icons/features/union.png
  documentation/static/icons/features/union@2x.png
  documentation/static/icons/features/universal.png
  documentation/static/icons/features/universal@2x.png
  documentation/static/icons/features/vector.png
  documentation/static/icons/features/vector@2x.png
Labels: review-required, auto-merge
