Repository refinedev/refine, pull requests merged in 2022-06, with the labels that each got.

#1865 fix(useTable): useTable creating nested <a> tag in Pagination component
  .changeset/fluffy-dolphins-tell.md
  packages/antd/src/hooks/table/useTable/useTable.ts
Labels: review-required, auto-merge

#1873 refactor: remove default values from refine contexts
  .changeset/late-gifts-camp.md
  documentation/docs/core/providers/i18n-provider.md
  examples/fineFoods/admin/src/components/header/index.tsx
  examples/i18n/nextjs/src/components/header/index.tsx
  examples/i18n/react/src/components/header/index.tsx
  packages/antd/src/providers/notificationProvider/index.spec.tsx
  packages/antd/test/index.tsx
  packages/core/src/components/containers/refine/index.tsx
  packages/core/src/components/pages/error/index.tsx
  packages/core/src/components/pages/login/index.tsx
  packages/core/src/components/routeChangeHandler/index.tsx
  packages/core/src/components/undoableQueue/index.tsx
  packages/core/src/contexts/accessControl/IAccessControlContext.ts
  packages/core/src/contexts/accessControl/index.tsx
  packages/core/src/contexts/auth/IAuthContext.ts
  packages/core/src/contexts/auth/index.tsx
  packages/core/src/contexts/notification/INotificationContext.ts
  packages/core/src/contexts/notification/index.tsx
  packages/core/src/contexts/translation/ITranslationContext.ts
  packages/core/src/contexts/translation/index.tsx
  packages/core/src/contexts/unsavedWarn/IUnsavedWarnContext.ts
  packages/core/src/contexts/unsavedWarn/index.tsx
  packages/core/src/hooks/accessControl/useCan/index.ts
  packages/core/src/hooks/accessControl/useCanWithoutCache.ts
  packages/core/src/hooks/auth/useAuthenticated/index.ts
  packages/core/src/hooks/auth/useGetIdentity/index.spec.ts
  packages/core/src/hooks/auth/useGetIdentity/index.ts
  packages/core/src/hooks/auth/useIsAuthenticated/index.ts
  packages/core/src/hooks/auth/useLogin/index.ts
  packages/core/src/hooks/auth/useLogout/index.ts
  packages/core/src/hooks/auth/usePermissions/index.ts
  packages/core/src/hooks/notification/useHandleNotification/index.ts
  packages/core/src/hooks/notification/useNotification/index.ts
  packages/core/src/hooks/refine/useWarnAboutChange/index.ts
  packages/core/src/hooks/translate/useGetLocale.spec.tsx
  packages/core/src/hooks/translate/useGetLocale.ts
  packages/core/src/hooks/translate/useSetLocale.ts
  packages/core/src/hooks/translate/useTranslate.ts
  packages/core/src/index.tsx
  packages/nextjs-router/src/checkAuthentication.ts
  packages/react-hook-form/src/useModalForm/index.ts
Labels: build examples

#1888 feat: extend `useTable.setFilters` function
  .changeset/forty-humans-carry.md
  .changeset/moody-pandas-pay.md
  .changeset/tiny-poets-nail.md
  documentation/docs/core/hooks/useTable.md
  packages/antd/src/hooks/table/useTable/useTable.ts
  packages/core/src/definitions/table/index.ts
  packages/core/src/hooks/useTable/index.spec.ts
  packages/core/src/hooks/useTable/index.ts
  packages/mui/src/hooks/useDataGrid/index.ts
Labels: build examples

#1866 docs: add `useStepsForm` documentation and example
  .changeset/shaggy-rice-deliver.md
  README.md
  documentation/blog/2022-03-22-refine-with-react95.md
  documentation/blog/2022-03-29-react-hook-form-upload.md
  documentation/docs/core/hooks/useForm.md
  documentation/docs/core/tutorial.md
  documentation/docs/examples/react-hook-form/useForm.md
  documentation/docs/examples/react-hook-form/useStepsForm.md
  documentation/docs/packages/react-hook-form/useForm.md
  documentation/docs/packages/react-hook-form/useStepsForm.md
  documentation/redirects.json
  documentation/sidebars.js
  documentation/static/img/packages/react-hook-form/useStepsForm/create-form.gif
  documentation/static/img/packages/react-hook-form/useStepsForm/edit-form.gif
  documentation/static/img/packages/react-hook-form/useStepsForm/list-page.png
  examples/reactHookForm/useForm/package.json
  examples/reactHookForm/useForm/public/favicon.ico
  examples/reactHookForm/useForm/public/index.html
  examples/reactHookForm/useForm/public/manifest.json
  examples/reactHookForm/useForm/src/App.tsx
  examples/reactHookForm/useForm/src/index.tsx
  examples/reactHookForm/useForm/src/interfaces/index.d.ts
  examples/reactHookForm/useForm/src/pages/posts/create.tsx
  examples/reactHookForm/useForm/src/pages/posts/edit.tsx
  examples/reactHookForm/useForm/src/pages/posts/index.tsx
  examples/reactHookForm/useForm/src/pages/posts/list.tsx
  examples/reactHookForm/useForm/src/react-app-env.d.ts
  examples/reactHookForm/useForm/tsconfig.json
  examples/reactHookForm/useStepsForm/package.json
  examples/reactHookForm/useStepsForm/public/favicon.ico
  examples/reactHookForm/useStepsForm/public/index.html
  examples/reactHookForm/useStepsForm/public/manifest.json
  examples/reactHookForm/useStepsForm/src/App.tsx
  examples/reactHookForm/useStepsForm/src/index.tsx
  examples/reactHookForm/useStepsForm/src/interfaces/index.d.ts
  examples/reactHookForm/useStepsForm/src/pages/posts/create.tsx
  examples/reactHookForm/useStepsForm/src/pages/posts/edit.tsx
  examples/reactHookForm/useStepsForm/src/pages/posts/index.tsx
  examples/reactHookForm/useStepsForm/src/pages/posts/list.tsx
  examples/reactHookForm/useStepsForm/src/react-app-env.d.ts
  examples/reactHookForm/useStepsForm/tsconfig.json
  packages/react-hook-form/README.md
  packages/react-hook-form/src/useStepsForm/index.ts
Labels: review-required, auto-merge

#1879 docs(buttons): creation of buttons docs
  documentation/docs/ui-frameworks/mui/components/buttons/clone.md
  documentation/docs/ui-frameworks/mui/components/buttons/create.md
  documentation/docs/ui-frameworks/mui/components/buttons/delete.md
  documentation/docs/ui-frameworks/mui/components/buttons/edit.md
  documentation/docs/ui-frameworks/mui/components/buttons/export.md
  documentation/docs/ui-frameworks/mui/components/buttons/import.md
  documentation/docs/ui-frameworks/mui/components/buttons/list.md
  documentation/docs/ui-frameworks/mui/components/buttons/refresh.md
  documentation/docs/ui-frameworks/mui/components/buttons/save.md
  documentation/docs/ui-frameworks/mui/components/buttons/show.md
  documentation/sidebars.js
  documentation/static/img/guides-and-concepts/components/buttons/clone/clone-mui.png
  documentation/static/img/guides-and-concepts/components/buttons/create/create-mui.png
  documentation/static/img/guides-and-concepts/components/buttons/delete/confirmation-mui.gif
  documentation/static/img/guides-and-concepts/components/buttons/delete/delete-mui.png
  documentation/static/img/guides-and-concepts/components/buttons/edit/edit-mui.png
  documentation/static/img/guides-and-concepts/components/buttons/export/export-mui.png
  documentation/static/img/guides-and-concepts/components/buttons/import/import-mui.png
  documentation/static/img/guides-and-concepts/components/buttons/list/list-mui.png
  documentation/static/img/guides-and-concepts/components/buttons/refresh/refresh-mui.png
  documentation/static/img/guides-and-concepts/components/buttons/save/save-mui.png
  documentation/static/img/guides-and-concepts/components/buttons/show/show-mui.png
Labels: pr-ready

#1896 Feat: lazy notification handle calls
  .changeset/cyan-avocados-tan.md
  .changeset/polite-crews-fry.md
  examples/fineFoods/admin/mui/src/App.tsx
  examples/fineFoods/admin/mui/src/index.tsx
  packages/core/src/components/containers/refine/index.tsx
  packages/mui/src/index.tsx
Labels: build examples

#1901 docs: field components documentation
  documentation/docs/ui-frameworks/mui/components/fields/boolean.md
  documentation/docs/ui-frameworks/mui/components/fields/date.md
  documentation/docs/ui-frameworks/mui/components/fields/email.md
  documentation/docs/ui-frameworks/mui/components/fields/file.md
  documentation/docs/ui-frameworks/mui/components/fields/markdown.md
  documentation/docs/ui-frameworks/mui/components/fields/number.md
  documentation/docs/ui-frameworks/mui/components/fields/tag.md
  documentation/docs/ui-frameworks/mui/components/fields/text.md
  documentation/docs/ui-frameworks/mui/components/fields/url.md
  documentation/sidebars.js
  documentation/static/img/guides-and-concepts/fields/boolean/booleanFieldMui.png
  documentation/static/img/guides-and-concepts/fields/date/dateFieldMui.png
  documentation/static/img/guides-and-concepts/fields/email/emailFieldMui.png
  documentation/static/img/guides-and-concepts/fields/file/fileFieldMui.png
  documentation/static/img/guides-and-concepts/fields/markdown/mardownFieldMui.png
  documentation/static/img/guides-and-concepts/fields/number/numberFieldMui.png
  documentation/static/img/guides-and-concepts/fields/tag/tagFieldMui.png
  documentation/static/img/guides-and-concepts/fields/text/textFieldMui.png
  documentation/static/img/guides-and-concepts/fields/url/urlFieldMui.png
Labels: pr-ready

#1916 fix: eslint react/display-name issue on examples
  examples/base/mui/src/pages/useModalForm/list.tsx
  examples/base/mui/src/pages/useStepsForm/list.tsx
  examples/baseHeadless/src/pages/posts/list.tsx
  examples/blog/win95/src/pages/posts/list.tsx
  examples/field/useSelect/mui/src/pages/posts/list.tsx
  examples/fineFoods/admin/mui/src/pages/categories/list.tsx
  examples/fineFoods/admin/mui/src/pages/couriers/list.tsx
  examples/fineFoods/admin/mui/src/pages/couriers/show.tsx
  examples/fineFoods/client/pages/[id]/[category]/index.tsx
  examples/reactTable/advanced/src/pages/posts/list.tsx
  examples/reactToastify/src/pages/posts/list.tsx
  examples/table/mui/advancedTable/src/pages/table/list.tsx
  examples/tutorial/headless/src/pages/posts/list.tsx
Labels: build examples

#1921 refactor: mui default sider
  .changeset/silver-spoons-battle.md
  packages/mui/src/components/layout/index.tsx
  packages/mui/src/components/layout/sider/index.spec.tsx
  packages/mui/src/components/layout/sider/index.tsx
Labels: pr-ready

#1953 docs: material ui theme guide
  documentation/docs/guides-and-concepts/theme/ant-design.md
  documentation/docs/guides-and-concepts/theme/material-ui.md
  documentation/redirects.json
  documentation/sidebars.js
  documentation/static/img/blog/2022-06-10-weve-raised-dollar1m-seed-funding/refine-500-2.png
  documentation/static/img/guides-and-concepts/theme/mui/customTheme.png
  documentation/static/img/guides-and-concepts/theme/mui/notistackTheme.gif
  documentation/static/img/guides-and-concepts/theme/mui/overridedTheme.png
  documentation/static/img/guides-and-concepts/theme/mui/toggleDarkMode.gif
  documentation/static/img/guides-and-concepts/theme/mui/withTheme.png
  documentation/static/img/guides-and-concepts/theme/mui/withoutTheme.png
Labels: pr-ready

#1974 style(buttons): fixing loading position, variant and colors
  packages/mui/src/components/buttons/delete/index.tsx
  packages/mui/src/components/buttons/export/index.tsx
  packages/mui/src/components/buttons/import/index.tsx
  packages/mui/src/components/buttons/refresh/index.tsx
  packages/mui/src/components/buttons/save/index.tsx
Labels: pr-ready

#1977 chore(buttons): changeset created
  .changeset/long-spies-tie.md
Labels: pr-ready

#1976 style(crud): spacing fix at the crud components
  .changeset/stupid-toes-hear.md
  packages/mui/src/components/crud/create/index.tsx
  packages/mui/src/components/crud/edit/index.tsx
  packages/mui/src/components/crud/list/__snapshots__/index.spec.tsx.snap
  packages/mui/src/components/crud/list/index.tsx
  packages/mui/src/components/crud/show/index.tsx
Labels: pr-ready

#1999 docs(theme): updated related docs with adding font family
  documentation/docs/ui-frameworks/mui/customization/theme.md
  documentation/docs/ui-frameworks/mui/tutorial.md
Labels: pr-ready

#2001 style(header): fixed header height
  examples/fineFoods/admin/mui/src/components/header/index.tsx
Labels: pr-ready

#2004 feat(header): default header component and state of render in layout
  packages/mui/src/components/layout/header/index.tsx
  packages/mui/src/components/layout/index.tsx
Labels: pr-ready

#2010 style(orderStatus): fix delivery status color on dark mode
  examples/fineFoods/admin/mui/src/components/orderStatus/index.tsx
Labels: pr-ready

#2018 docs(tutorial): tutorial updated with react-hook-form info
  documentation/docs/ui-frameworks/mui/tutorial.md
Labels: pr-ready

#2025 refactor(components): update TSDocs
  packages/mui/src/components/buttons/clone/index.tsx
  packages/mui/src/components/buttons/create/index.tsx
  packages/mui/src/components/buttons/delete/index.tsx
  packages/mui/src/components/buttons/edit/index.tsx
  packages/mui/src/components/buttons/export/index.tsx
  packages/mui/src/components/buttons/import/index.tsx
  packages/mui/src/components/buttons/list/index.tsx
  packages/mui/src/components/buttons/refresh/index.tsx
  packages/mui/src/components/buttons/save/index.tsx
  packages/mui/src/components/buttons/show/index.tsx
  packages/mui/src/components/crud/create/index.tsx
  packages/mui/src/components/crud/edit/index.tsx
  packages/mui/src/components/crud/list/index.tsx
  packages/mui/src/components/crud/show/index.tsx
  packages/mui/src/components/fields/boolean/index.tsx
  packages/mui/src/components/fields/date/index.tsx
  packages/mui/src/components/fields/email/index.tsx
  packages/mui/src/components/fields/file/index.tsx
  packages/mui/src/components/fields/markdown/index.tsx
  packages/mui/src/components/fields/number/index.tsx
  packages/mui/src/components/fields/tag/index.tsx
  packages/mui/src/components/fields/text/index.tsx
  packages/mui/src/components/fields/url/index.tsx
Labels: pr-ready

#2029 refactor(default-login-pages): updating texts with translations
  .changeset/funny-onions-itch.md
  packages/core/src/components/pages/login/index.tsx
  packages/mui/src/components/pages/login/index.tsx
Labels: pr-ready

#2033 refactor(buttons-variant): fix the variant of delete button
  .changeset/metal-hotels-tap.md
  examples/tutorial/mui/src/pages/posts/list.tsx
  packages/mui/src/components/buttons/delete/index.tsx
  packages/mui/src/components/crud/edit/index.tsx
Labels: pr-ready

#2035 style(product-page): fix the grid layout for responsive behaviour
  examples/fineFoods/admin/mui/src/components/product/item.tsx
  examples/fineFoods/admin/mui/src/pages/products/list.tsx
Labels: pr-ready

#2040 docs(tutorial-example): ordered tutorials
  documentation/docs/examples/tutorial/antd-tutorial.md
  documentation/docs/examples/tutorial/headless-tutorial.md
  documentation/docs/examples/tutorial/mui-tutorial.md
  documentation/docs/getting-started/learn-basics.md
  documentation/docs/getting-started/overview.md
  documentation/docusaurus.config.js
  documentation/redirects.json
  documentation/sidebars.js
Labels: pr-ready

#2061 fix: common `Link` usage for nextjs and react applications
  .changeset/dull-lizards-add.md
  .changeset/loud-spiders-share.md
  documentation/docs/core/hooks/ui/useMenu.md
  documentation/docs/core/providers/router-provider.md
  documentation/docs/guides-and-concepts/multi-tenancy/appwrite.md
  documentation/docs/guides-and-concepts/multi-tenancy/strapi.md
  documentation/docs/guides-and-concepts/real-time.md
  documentation/docs/ui-frameworks/antd/customization/sider.md
  documentation/docs/ui-frameworks/mui/customization/sider.md
  examples/ably/src/components/sider/index.tsx
  examples/customization/customSider/src/components/sider/index.tsx
  examples/customization/offLayoutArea/src/components/sider/index.tsx
  examples/multi-tenancy/appwrite/src/components/sider/index.tsx
  examples/multi-tenancy/strapi/src/components/sider/index.tsx
  packages/antd/src/components/breadcrumb/index.tsx
  packages/antd/src/components/buttons/clone/index.tsx
  packages/antd/src/components/buttons/create/index.tsx
  packages/antd/src/components/buttons/edit/index.tsx
  packages/antd/src/components/buttons/list/index.tsx
  packages/antd/src/components/buttons/show/index.tsx
  packages/antd/src/components/layout/sider/index.tsx
  packages/antd/src/components/layout/title/index.tsx
  packages/antd/src/hooks/table/useTable/paginationLink.tsx
  packages/mui/src/components/breadcrumb/index.tsx
  packages/mui/src/components/buttons/clone/index.tsx
  packages/mui/src/components/buttons/create/index.tsx
  packages/mui/src/components/buttons/edit/index.tsx
  packages/mui/src/components/buttons/list/index.tsx
  packages/mui/src/components/buttons/show/index.tsx
  packages/mui/src/components/layout/sider/index.tsx
  packages/mui/src/components/layout/title/index.tsx
  packages/nextjs-router/src/index.ts
  packages/nextjs-router/src/refineLink.tsx
  packages/nextjs-router/src/routerProvider.ts
Labels: build examples

#2050 feat: ability to enable/disable pagination in `useTable` hooks
  .changeset/chatty-peaches-cheer.md
  .changeset/four-lions-leave.md
  .changeset/green-poems-grab.md
  .changeset/silly-garlics-listen.md
  .changeset/small-eggs-wash.md
  .changeset/stupid-meals-yell.md
  examples/dataProvider/strapi-v4/src/App.tsx
  examples/dataProvider/strapi-v4/src/pages/users/index.ts
  examples/dataProvider/strapi-v4/src/pages/users/list.tsx
  packages/airtable/src/index.ts
  packages/altogic/src/index.ts
  packages/antd/src/hooks/table/useTable/useTable.spec.ts
  packages/antd/src/hooks/table/useTable/useTable.ts
  packages/appwrite/src/index.ts
  packages/core/src/contexts/data/IDataContext.ts
  packages/core/src/definitions/table/index.ts
  packages/core/src/hooks/data/useList.ts
  packages/core/src/hooks/useTable/index.spec.ts
  packages/core/src/hooks/useTable/index.ts
  packages/graphql/src/index.ts
  packages/hasura/src/index.ts
  packages/mui/src/hooks/useDataGrid/index.spec.ts
  packages/mui/src/hooks/useDataGrid/index.ts
  packages/nestjsx-crud/src/index.ts
  packages/nhost/src/index.ts
  packages/react-table/src/useTable/index.ts
  packages/simple-rest/src/index.ts
  packages/strapi-graphql/src/index.ts
  packages/strapi-v4/src/dataProvider.ts
  packages/strapi/src/dataProvider.ts
  packages/supabase/src/index.ts
Labels: bug, build examples
