Repository refinedev/refine, pull requests merged in 2023-02, with the labels that each got.

#3557 fix: `getColumn` is possibly `undefined`
  examples/auth-headless/src/pages/posts/list.tsx
  examples/base-headless/src/pages/posts/list.tsx
  examples/finefoods-mui/src/components/dashboard/orderTimeline/index.tsx
  examples/table-mui-advanced/src/pages/table/index.tsx
  examples/table-react-table-advanced/src/pages/posts/list.tsx
  examples/with-persist-query/src/pages/posts/list.tsx
  examples/with-react-toastify/src/pages/posts/list.tsx
  examples/with-remix-headless/app/pages/posts/list.tsx
Labels: build examples

#3567 feat(v4): support audit log in many hooks (useCreateMany, useDeleteMany, useUpdateMany)
  .changeset/early-bananas-reflect.md
  documentation/docs/api-reference/core/providers/audit-log-provider.md
  packages/core/src/hooks/data/useCreate.spec.tsx
  packages/core/src/hooks/data/useCreateMany.spec.tsx
  packages/core/src/hooks/data/useCreateMany.ts
  packages/core/src/hooks/data/useDelete.spec.tsx
  packages/core/src/hooks/data/useDeleteMany.spec.tsx
  packages/core/src/hooks/data/useDeleteMany.ts
  packages/core/src/hooks/data/useUpdate.ts
  packages/core/src/hooks/data/useUpdateMany.spec.tsx
  packages/core/src/hooks/data/useUpdateMany.ts
Labels: build examples, v4

#3589 fix: supabase auth provider checkAuth method
  documentation/docs/advanced-tutorials/data-provider/supabase.md
  examples/blog-hackathonize/src/authProvider.ts
  examples/blog-issue-tracker/src/authProvider.ts
  examples/blog-refine-supabase-auth/src/authProvider.ts
  examples/blog-refineflix/src/authProvider.ts
  examples/blog-win95/src/authProvider.ts
  examples/data-provider-supabase/src/App.tsx
  examples/pixels-admin/src/providers/authProvider.ts
  examples/pixels/src/providers/authProvider.ts
Labels: build examples

#3568 feat(v4): add generic to option label-value on `useSelect`
  .changeset/tall-crews-poke.md
  examples/finefoods-antd/src/pages/orders/list.tsx
  packages/core/src/hooks/useSelect/index.ts
Labels: build examples, v4

#3571 feat(v4): `hasPagination` default value set to `false` on `useSelect`
  .changeset/swift-cycles-marry.md
  documentation/docs/api-reference/antd/hooks/field/useSelect/index.md
  documentation/docs/api-reference/core/hooks/useSelect/index.md
  documentation/docs/api-reference/mantine/hooks/useSelect/index.md
  documentation/docs/api-reference/mui/hooks/useAutocomplete/index.md
  examples/table-mui-advanced/src/pages/dataGrid/index.tsx
  examples/table-mui-use-data-grid/src/pages/posts/list.tsx
  examples/table-mui-use-update-many/src/pages/posts/list.tsx
  packages/core/src/hooks/useSelect/index.spec.ts
  packages/core/src/hooks/useSelect/index.ts
Labels: build examples, v4

#3580 feat(v4): change resource `options` to `meta` (#3561)
  .changeset/early-pigs-decide.md
  .changeset/great-moose-jump.md
  .changeset/many-lobsters-laugh.md
  .changeset/mean-kangaroos-press.md
  documentation/blog/2021-10-4-simple-web-application.md
  documentation/blog/2022-02-22-refine-invoice-genarator.md
  documentation/docs/advanced-tutorials/data-provider/appwrite.md
  documentation/docs/advanced-tutorials/multi-level-menu/multi-level-menu.md
  documentation/docs/advanced-tutorials/multi-tenancy/appwrite.md
  documentation/docs/api-reference/core/components/refine-config.md
  documentation/docs/api-reference/core/hooks/resource/useResource.md
  documentation/docs/api-reference/core/hooks/ui/useMenu.md
  documentation/docs/api-reference/core/interfaces.md
  documentation/docs/api-reference/core/providers/accessControl-provider.md
  documentation/docs/api-reference/core/providers/audit-log-provider.md
  documentation/docs/api-reference/core/providers/data-provider.md
  packages/antd-audit-log/src/components/logList/index.tsx
  packages/antd/src/hooks/useMenu/useMenu.spec.tsx
  packages/cloud/src/hooks/useResourcesConfig/index.spec.tsx
  packages/cloud/test/__mocks__/@pankod/refine-sdk.ts
  packages/core/src/components/containers/refine/index.tsx
  packages/core/src/contexts/resource/IResourceContext.ts
  packages/core/src/definitions/helpers/pickDataProvider/index.spec.ts
  packages/core/src/definitions/helpers/pickDataProvider/index.ts
  packages/core/src/definitions/helpers/routeGenerator/index.ts
  packages/core/src/definitions/helpers/treeView/createTreeView/index.spec.ts
  packages/core/src/definitions/helpers/treeView/createTreeView/index.ts
  packages/core/src/hooks/auditLog/useLog/index.spec.ts
  packages/core/src/hooks/auditLog/useLog/index.ts
  packages/core/src/hooks/menu/useMenu.spec.tsx
  packages/core/src/hooks/menu/useMenu.tsx
  packages/core/src/hooks/resource/useResource/index.spec.tsx
  packages/inferencer/src/utilities/pick-data-provider/index.tsx
  packages/mui/src/hooks/useMenu/useMenu.spec.tsx
  packages/sdk/src/interfaces/index.ts
  packages/sdk/test/config/index.mock.ts
  packages/sdk/test/config/index.spec.ts
  packages/sdk/test/draft-resource/index.mock.ts
  packages/ui-tests/src/tests/buttons/clone.tsx
  packages/ui-tests/src/tests/buttons/create.tsx
  packages/ui-tests/src/tests/buttons/edit.tsx
  packages/ui-tests/src/tests/buttons/list.tsx
  packages/ui-tests/src/tests/buttons/show.tsx
  packages/ui-tests/src/tests/crud/create.tsx
  packages/ui-tests/src/tests/crud/list.tsx
Labels: build examples, v4

#3593 feat(v4-antd-mui): remove useMenu
  .changeset/eighty-pianos-itch.md
  .changeset/metal-comics-watch.md
  .changeset/tiny-crabs-drop.md
  packages/antd/src/hooks/index.ts
  packages/antd/src/hooks/useMenu/index.tsx
  packages/antd/src/hooks/useMenu/useMenu.spec.tsx
  packages/codemod/src/index.ts
  packages/codemod/src/transformations/use-menu-to-core.ts
  packages/mui/src/hooks/index.ts
  packages/mui/src/hooks/useMenu/index.tsx
  packages/mui/src/hooks/useMenu/useMenu.spec.tsx
Labels: v4

#3636 fix: update date inferencer to check existence of date separators
  .changeset/tender-ravens-battle.md
  packages/inferencer/src/field-inferencers/date.test.ts
  packages/inferencer/src/field-inferencers/date.ts
Labels: bug

#3649 feat(v4): codemod deprecations
  packages/codemod/package.json
  packages/codemod/src/index.ts
  packages/codemod/src/transformations/fix-v4-deprecations.ts
Labels: v4

#3653 docs(blog): add react admin panel article
  documentation/blog/2023-02-23-refine-strapi-mantine.md
  examples/access-control-casbin/config-overrides.js
  examples/blog-react-admin-mantine/.gitignore
  examples/blog-react-admin-mantine/.npmrc
  examples/blog-react-admin-mantine/README.MD
  examples/blog-react-admin-mantine/package.json
  examples/blog-react-admin-mantine/public/favicon.ico
  examples/blog-react-admin-mantine/public/index.html
  examples/blog-react-admin-mantine/src/App.tsx
  examples/blog-react-admin-mantine/src/authProvider.ts
  examples/blog-react-admin-mantine/src/constants.ts
  examples/blog-react-admin-mantine/src/index.tsx
  examples/blog-react-admin-mantine/src/interfaces/index.d.ts
  examples/blog-react-admin-mantine/src/meta.json
  examples/blog-react-admin-mantine/src/pages/posts/create.tsx
  examples/blog-react-admin-mantine/src/pages/posts/edit.tsx
  examples/blog-react-admin-mantine/src/pages/posts/index.tsx
  examples/blog-react-admin-mantine/src/pages/posts/list.tsx
  examples/blog-react-admin-mantine/src/react-app-env.d.ts
  examples/blog-react-admin-mantine/src/reportWebVitals.ts
  examples/blog-react-admin-mantine/src/setupTests.ts
  examples/blog-react-admin-mantine/tsconfig.json
  examples/pixels-admin/config-overrides.js
Labels: build examples

#3654 fix(v4): reorganize `useTable` props
  documentation/blog/2021-10-4-admin-panel-with-nestjs.md
  documentation/blog/2021-10-4-feedback-admin-panel.md
  documentation/blog/2021-10-4-simple-web-application.md
  documentation/blog/2021-10-6-migrating-react-admin-application-to-refine.md
  documentation/blog/2021-11-26-refine-vs-react-admin.md
  documentation/blog/2021-11-29-refine-vs-admin-bro.md
  documentation/blog/2022-02-21-build-internal-tools-with-refine.md
  documentation/blog/2022-08-23-mui-usedatagrid.md
  documentation/blog/2023-02-16-refine-pixels-3.md
  documentation/docs/advanced-tutorials/data-provider/appwrite.md
  documentation/docs/advanced-tutorials/data-provider/graphql.md
  documentation/docs/advanced-tutorials/data-provider/supabase.md
  documentation/docs/advanced-tutorials/multi-tenancy/appwrite.md
  documentation/docs/advanced-tutorials/multi-tenancy/strapi.md
  documentation/docs/api-reference/antd/components/filter-dropdown.md
  documentation/docs/api-reference/antd/hooks/list/filtering-live-preview.md
  documentation/docs/api-reference/antd/hooks/list/sorting-live-preview.md
  documentation/docs/api-reference/antd/hooks/list/useSimpleList.md
  documentation/docs/api-reference/antd/hooks/table/_partial-use-table-sorter-live-preview.md
  documentation/docs/api-reference/antd/hooks/table/useTable.md
  documentation/docs/api-reference/core/hooks/useTable/_partial-sorting-live-preview.md
  documentation/docs/api-reference/core/hooks/useTable/index.md
  documentation/docs/api-reference/mui/hooks/useDataGrid/_partial-use-data-grid-relational-live-preview.md
  documentation/docs/api-reference/mui/hooks/useDataGrid/index.md
  documentation/docs/packages/documentation/react-hook-form/useForm.md
  documentation/docs/packages/documentation/react-hook-form/useModalForm.md
  documentation/docs/packages/documentation/react-hook-form/useStepsForm.md
  documentation/docs/packages/documentation/react-table/index.md
  packages/antd/src/hooks/list/useSimpleList/useSimpleList.ts
  packages/antd/src/hooks/table/useTable/useTable.spec.ts
  packages/antd/src/hooks/table/useTable/useTable.ts
  packages/codemod/src/transformations/fix-v4-deprecations.ts
  packages/core/src/hooks/useTable/index.spec.ts
  packages/core/src/hooks/useTable/index.ts
  packages/mui/src/hooks/useDataGrid/index.ts
  packages/react-table/src/useTable/index.spec.ts
Labels: v4
