Repository refinedev/refine, pull requests merged in 2024-03, with the labels that each got.

#5508 fix(hasura): nested sorting abilities
  .changeset/hungry-readers-begin.md
  packages/hasura/src/utils/generateSorting.ts
  packages/hasura/test/utils/generateSorting.spec.ts
Labels: invalid

#5609 feat(core): ability to pass an argument to usePermissions
  .changeset/metal-bears-perform.md
  documentation/docs/authentication/auth-provider/index.md
  documentation/docs/authentication/hooks/use-permissions/index.md
  documentation/docs/guides-concepts/authentication/auth-provider-interface.md
  examples/auth-antd/src/App.tsx
  examples/auth-antd/src/pages/dashboard.tsx
  packages/core/src/contexts/auth/IAuthContext.ts
  packages/core/src/hooks/auth/usePermissions/index.spec.ts
  packages/core/src/hooks/auth/usePermissions/index.ts
  packages/core/src/interfaces/bindings/auth.ts
Labels: build examples

#5739 chore(inferencer-cli): remove redundant type usage `IResourceComponentsProps`
  .changeset/popular-otters-lick.md
  .changeset/slimy-wombats-dream.md
  packages/cli/templates/resource/create.tsx.hbs
  packages/cli/templates/resource/edit.tsx.hbs
  packages/cli/templates/resource/list.tsx.hbs
  packages/cli/templates/resource/show.tsx.hbs
  packages/inferencer/src/inferencers/antd/create.tsx
  packages/inferencer/src/inferencers/antd/edit.tsx
  packages/inferencer/src/inferencers/antd/list.tsx
  packages/inferencer/src/inferencers/antd/show.tsx
  packages/inferencer/src/inferencers/chakra-ui/__tests__/__snapshots__/create.test.tsx.snap
  packages/inferencer/src/inferencers/chakra-ui/__tests__/__snapshots__/edit.test.tsx.snap
  packages/inferencer/src/inferencers/chakra-ui/__tests__/__snapshots__/index.test.tsx.snap
  packages/inferencer/src/inferencers/chakra-ui/__tests__/__snapshots__/list.test.tsx.snap
  packages/inferencer/src/inferencers/chakra-ui/__tests__/__snapshots__/show.test.tsx.snap
  packages/inferencer/src/inferencers/chakra-ui/create.tsx
  packages/inferencer/src/inferencers/chakra-ui/edit.tsx
  packages/inferencer/src/inferencers/chakra-ui/list.tsx
  packages/inferencer/src/inferencers/chakra-ui/show.tsx
  packages/inferencer/src/inferencers/headless/__tests__/__snapshots__/create.test.tsx.snap
  packages/inferencer/src/inferencers/headless/__tests__/__snapshots__/edit.test.tsx.snap
  packages/inferencer/src/inferencers/headless/__tests__/__snapshots__/index.test.tsx.snap
  packages/inferencer/src/inferencers/headless/__tests__/__snapshots__/list.test.tsx.snap
  packages/inferencer/src/inferencers/headless/__tests__/__snapshots__/show.test.tsx.snap
  packages/inferencer/src/inferencers/headless/create.tsx
  packages/inferencer/src/inferencers/headless/edit.tsx
  packages/inferencer/src/inferencers/headless/list.tsx
  packages/inferencer/src/inferencers/headless/show.tsx
  packages/inferencer/src/inferencers/mantine/__tests__/__snapshots__/create.test.tsx.snap
  packages/inferencer/src/inferencers/mantine/__tests__/__snapshots__/edit.test.tsx.snap
  packages/inferencer/src/inferencers/mantine/__tests__/__snapshots__/index.test.tsx.snap
  packages/inferencer/src/inferencers/mantine/__tests__/__snapshots__/list.test.tsx.snap
  packages/inferencer/src/inferencers/mantine/__tests__/__snapshots__/show.test.tsx.snap
  packages/inferencer/src/inferencers/mantine/create.tsx
  packages/inferencer/src/inferencers/mantine/edit.tsx
  packages/inferencer/src/inferencers/mantine/list.tsx
  packages/inferencer/src/inferencers/mantine/show.tsx
  packages/inferencer/src/inferencers/mui/__snapshots__/index.test.tsx.snap
  packages/inferencer/src/inferencers/mui/__tests__/__snapshots__/create.test.tsx.snap
  packages/inferencer/src/inferencers/mui/__tests__/__snapshots__/edit.test.tsx.snap
  packages/inferencer/src/inferencers/mui/__tests__/__snapshots__/list.test.tsx.snap
  packages/inferencer/src/inferencers/mui/__tests__/__snapshots__/show.test.tsx.snap
  packages/inferencer/src/inferencers/mui/create.tsx
  packages/inferencer/src/inferencers/mui/edit.tsx
  packages/inferencer/src/inferencers/mui/list.tsx
  packages/inferencer/src/inferencers/mui/show.tsx
Labels: ready-for-release

#5733 feat(core): add use translation hook
  .changeset/friendly-kids-hug.md
  documentation/docs/guides-concepts/i18n/i18n-headless.tsx
  documentation/docs/guides-concepts/i18n/index.md
  documentation/docs/i18n/hooks/use-get-locale/index.md
  documentation/docs/i18n/hooks/use-set-locale/index.md
  documentation/docs/i18n/hooks/use-translate/index.md
  documentation/docs/i18n/hooks/use-translation/index.md
  documentation/docs/i18n/i18n-provider/index.md
  documentation/redirects.json
  documentation/sidebars.js
  documentation/versioned_docs/version-3.xx.xx/api-reference/core/hooks/auth/useCheckError.md
  examples/i18n-nextjs/src/app/blog-posts/edit/[id]/page.tsx
  examples/i18n-nextjs/src/app/blog-posts/page.tsx
  examples/i18n-nextjs/src/app/blog-posts/show/[id]/page.tsx
  examples/i18n-nextjs/src/app/categories/create/page.tsx
  examples/i18n-nextjs/src/app/categories/edit/[id]/page.tsx
  examples/i18n-nextjs/src/app/categories/show/[id]/page.tsx
  examples/i18n-nextjs/src/components/header/index.tsx
  examples/i18n-react/src/components/header/index.tsx
  examples/i18n-react/src/pages/posts/create.tsx
  examples/i18n-react/src/pages/posts/edit.tsx
  examples/i18n-react/src/pages/posts/list.tsx
  examples/i18n-react/src/pages/posts/show.tsx
  packages/core/src/hooks/i18n/index.ts
  packages/core/src/hooks/i18n/useTranslation.spec.tsx
  packages/core/src/hooks/i18n/useTranslation.tsx
Labels: ready-for-release
